export interface SEOMetadata {
  title: string;
  description: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: string;
  twitterCard?: "summary" | "summary_large_image";
  keywords?: string[];
  canonical?: string;
}

export const DEFAULT_SEO: SEOMetadata = {
  title: "QuantEdge Research | AI-Powered Trading Research Platform",
  description: "Discover trading opportunities with QuantEdge's dual-engine approach: AI-powered analysis and quantitative signals for stocks, options, and crypto.",
  ogImage: "/og-image.png",
  twitterCard: "summary_large_image",
  keywords: ["trading research", "quantitative signals", "AI trading", "market analysis", "stock trading", "options trading", "crypto trading"],
};

export const PAGE_SEO: Record<string, SEOMetadata> = {
  landing: {
    title: "QuantEdge Research | AI-Powered Trading Research Platform",
    description: "Discover day trading opportunities with QuantEdge's dual-engine approach combining AI-powered analysis and quantitative signals for stocks, options, and crypto.",
    ogTitle: "QuantEdge Research - 2 Engines, 1 Edge",
    ogDescription: "AI + Quantitative trading research platform. Get real-time signals, chart analysis, and market insights.",
    keywords: ["trading research", "AI trading platform", "quantitative analysis", "day trading signals", "market research"],
  },
  pricing: {
    title: "Pricing Plans | QuantEdge Research",
    description: "Choose the right QuantEdge plan for your trading needs. From free access to advanced analytics and pro features for serious traders.",
    ogTitle: "QuantEdge Pricing - Plans for Every Trader",
    ogDescription: "Flexible pricing plans with real-time data, AI analysis, and quantitative signals. Start free or upgrade for full access.",
    keywords: ["trading platform pricing", "trading subscription", "market research pricing"],
  },
  about: {
    title: "About | QuantEdge Research",
    description: "Learn about the creator behind QuantEdge Research - a Model Risk Engineer building AI-powered trading tools.",
    ogTitle: "About QuantEdge Research",
    ogDescription: "Meet the team behind the dual-engine trading research platform combining AI and quantitative analysis.",
    keywords: ["about QuantEdge", "trading platform team", "fintech startup"],
  },
  blog: {
    title: "Blog | QuantEdge Research",
    description: "Trading insights, market analysis, and platform updates from QuantEdge Research. Learn AI trading strategies and quantitative methods.",
    ogTitle: "QuantEdge Blog - Trading Insights & Analysis",
    ogDescription: "Expert trading insights, market analysis, and educational content for day traders and investors.",
    keywords: ["trading blog", "market analysis", "trading education", "AI trading insights"],
  },
  successStories: {
    title: "Success Stories | QuantEdge Research",
    description: "Real winning trades from QuantEdge's AI and quantitative engines. See verified performance and trade results.",
    ogTitle: "QuantEdge Success Stories - Real Trading Results",
    ogDescription: "Browse verified winning trades generated by our AI and quantitative analysis engines.",
    keywords: ["trading success", "winning trades", "trade performance", "trading results"],
  },
  tradeDesk: {
    title: "Trade Desk | QuantEdge Research",
    description: "Access real-time trading signals, AI-generated ideas, and quantitative analysis on the QuantEdge Trade Desk.",
    ogTitle: "QuantEdge Trade Desk",
    ogDescription: "Your command center for AI and quantitative trading signals.",
    keywords: ["trade desk", "trading signals", "real-time analysis"],
  },
  performance: {
    title: "Performance Analytics | QuantEdge Research",
    description: "Track signal performance, win rates, and analytics across all QuantEdge trading engines.",
    ogTitle: "QuantEdge Performance Metrics",
    ogDescription: "Transparent performance tracking for AI and quantitative trading signals.",
    keywords: ["trading performance", "win rate analytics", "signal performance"],
  },
  chartAnalysis: {
    title: "Chart Analysis | QuantEdge Research",
    description: "Upload trading charts for instant AI-powered pattern recognition and technical analysis.",
    ogTitle: "AI Chart Analysis - QuantEdge",
    ogDescription: "Get instant chart pattern recognition and technical analysis powered by AI.",
    keywords: ["chart analysis", "pattern recognition", "technical analysis", "AI chart reading"],
  },
  academy: {
    title: "Trading Academy | QuantEdge Research",
    description: "Learn trading strategies, quantitative methods, and AI-powered analysis techniques at QuantEdge Academy.",
    ogTitle: "QuantEdge Academy - Learn Trading",
    ogDescription: "Master trading with courses on AI signals, quantitative strategies, and risk management.",
    keywords: ["trading education", "trading courses", "learn trading", "trading academy"],
  },
};

export function generateSEO(pageKey?: string, overrides?: Partial<SEOMetadata>): SEOMetadata {
  const pageSeo: Partial<SEOMetadata> = pageKey && PAGE_SEO[pageKey] ? PAGE_SEO[pageKey] : {};
  
  return {
    ...DEFAULT_SEO,
    ...pageSeo,
    ...overrides,
    ogTitle: overrides?.ogTitle || pageSeo.ogTitle || overrides?.title || pageSeo.title || DEFAULT_SEO.title,
    ogDescription: overrides?.ogDescription || pageSeo.ogDescription || overrides?.description || pageSeo.description || DEFAULT_SEO.description,
  };
}

export function formatTitle(title: string, siteName: string = "QuantEdge Research"): string {
  if (title.includes(siteName)) return title;
  return `${title} | ${siteName}`;
}
