CREATE TABLE "catalysts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"symbol" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"source" text NOT NULL,
	"source_url" text,
	"timestamp" text NOT NULL,
	"event_type" text NOT NULL,
	"impact" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "futures_contracts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"root_symbol" text NOT NULL,
	"contract_code" text NOT NULL,
	"exchange" text NOT NULL,
	"expiration_date" text NOT NULL,
	"multiplier" real NOT NULL,
	"tick_size" real NOT NULL,
	"tick_value" real NOT NULL,
	"initial_margin" real NOT NULL,
	"maintenance_margin" real NOT NULL,
	"is_front_month" boolean DEFAULT false,
	"roll_date" text,
	"description" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "futures_contracts_contract_code_unique" UNIQUE("contract_code")
);
--> statement-breakpoint
CREATE TABLE "market_data" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"symbol" text NOT NULL,
	"asset_type" text NOT NULL,
	"current_price" real NOT NULL,
	"change_percent" real NOT NULL,
	"volume" real NOT NULL,
	"market_cap" real,
	"session" text NOT NULL,
	"timestamp" text NOT NULL,
	"high_24h" real,
	"low_24h" real,
	"high_52_week" real,
	"low_52_week" real,
	"avg_volume" real,
	"data_source" text DEFAULT 'seed' NOT NULL,
	"last_updated" text NOT NULL,
	CONSTRAINT "market_data_symbol_unique" UNIQUE("symbol")
);
--> statement-breakpoint
CREATE TABLE "model_cards" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"engine_version" text NOT NULL,
	"ml_weights_version" text,
	"model_type" text NOT NULL,
	"description" text NOT NULL,
	"created_at" text NOT NULL,
	"created_by" text,
	"assumptions" text,
	"data_limitations" text,
	"signal_weights" text,
	"backtest_start_date" text,
	"backtest_end_date" text,
	"backtest_win_rate" real,
	"backtest_sharpe_ratio" real,
	"backtest_max_drawdown" real,
	"live_trades_generated" integer DEFAULT 0,
	"live_win_rate" real,
	"live_accuracy_rate" real,
	"status" text DEFAULT 'active' NOT NULL,
	"deprecated_at" text,
	"deprecation_reason" text,
	CONSTRAINT "model_cards_engine_version_unique" UNIQUE("engine_version")
);
--> statement-breakpoint
CREATE TABLE "options_data" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"symbol" text NOT NULL,
	"strike_price" real NOT NULL,
	"expiry_date" text NOT NULL,
	"option_type" text NOT NULL,
	"implied_volatility" real NOT NULL,
	"open_interest" integer NOT NULL,
	"volume" integer NOT NULL,
	"bid" real NOT NULL,
	"ask" real NOT NULL,
	"last_price" real NOT NULL,
	"delta" real,
	"gamma" real,
	"theta" real,
	"vega" real
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"sid" varchar PRIMARY KEY NOT NULL,
	"sess" jsonb NOT NULL,
	"expire" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trade_ideas" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar,
	"symbol" text NOT NULL,
	"asset_type" text NOT NULL,
	"direction" text NOT NULL,
	"holding_period" text DEFAULT 'day' NOT NULL,
	"entry_price" real NOT NULL,
	"target_price" real NOT NULL,
	"stop_loss" real NOT NULL,
	"risk_reward_ratio" real NOT NULL,
	"catalyst" text NOT NULL,
	"catalyst_source_url" text,
	"analysis" text NOT NULL,
	"liquidity_warning" boolean DEFAULT false,
	"session_context" text NOT NULL,
	"timestamp" text NOT NULL,
	"is_public" boolean DEFAULT false,
	"visibility" text DEFAULT 'private' NOT NULL,
	"entry_valid_until" text,
	"exit_by" text,
	"expiry_date" text,
	"strike_price" real,
	"option_type" text,
	"futures_contract_code" text,
	"futures_root_symbol" text,
	"futures_multiplier" real,
	"futures_tick_size" real,
	"futures_initial_margin" real,
	"futures_maintenance_margin" real,
	"source" text DEFAULT 'quant' NOT NULL,
	"confidence_score" real DEFAULT 0 NOT NULL,
	"quality_signals" text[],
	"probability_band" text DEFAULT 'C' NOT NULL,
	"outcome_status" text DEFAULT 'open',
	"exit_price" real,
	"realized_pnl" real,
	"exit_date" text,
	"outcome_notes" text,
	"resolution_reason" text,
	"actual_holding_time_minutes" integer,
	"percent_gain" real,
	"validated_at" text,
	"prediction_accurate" boolean,
	"prediction_accuracy_percent" real,
	"prediction_validated_at" text,
	"highest_price_reached" real,
	"lowest_price_reached" real,
	"exclude_from_training" boolean DEFAULT false,
	"engine_version" text,
	"ml_weights_version" text,
	"generation_timestamp" text,
	"data_source_used" text,
	"rsi_value" real,
	"macd_line" real,
	"macd_signal" real,
	"macd_histogram" real,
	"volume_ratio" real,
	"price_vs_52week_high" real,
	"price_vs_52week_low" real,
	"volatility_regime" text,
	"session_phase" text,
	"trend_strength" real,
	"entry_window_minutes" integer,
	"exit_window_minutes" integer,
	"timing_confidence" real,
	"target_hit_probability" real,
	"is_news_catalyst" boolean DEFAULT false,
	"is_lotto_play" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "user_preferences" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"account_size" real DEFAULT 10000 NOT NULL,
	"max_risk_per_trade" real DEFAULT 1 NOT NULL,
	"default_capital_per_idea" real DEFAULT 1000 NOT NULL,
	"default_options_budget" real DEFAULT 250 NOT NULL,
	"preferred_assets" text[] DEFAULT '{"stock","option","crypto"}' NOT NULL,
	"holding_horizon" text DEFAULT 'intraday' NOT NULL,
	"theme" text DEFAULT 'dark' NOT NULL,
	"timezone" text DEFAULT 'America/Chicago' NOT NULL,
	"default_view_mode" text DEFAULT 'card' NOT NULL,
	"compact_mode" boolean DEFAULT false NOT NULL,
	"discord_webhook_url" text,
	"enable_trade_alerts" boolean DEFAULT true NOT NULL,
	"enable_price_alerts" boolean DEFAULT true NOT NULL,
	"enable_performance_alerts" boolean DEFAULT false NOT NULL,
	"enable_weekly_report" boolean DEFAULT false NOT NULL,
	"default_asset_filter" text DEFAULT 'all' NOT NULL,
	"default_confidence_filter" text DEFAULT 'all' NOT NULL,
	"auto_refresh_enabled" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "user_preferences_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar,
	"first_name" varchar,
	"last_name" varchar,
	"profile_image_url" varchar,
	"discord_user_id" varchar,
	"discord_username" varchar,
	"subscription_tier" text DEFAULT 'free' NOT NULL,
	"subscription_status" varchar DEFAULT 'active',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "watchlist" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar,
	"symbol" text NOT NULL,
	"asset_type" text NOT NULL,
	"target_price" real,
	"notes" text,
	"added_at" text NOT NULL,
	"entry_alert_price" real,
	"stop_alert_price" real,
	"target_alert_price" real,
	"alerts_enabled" boolean DEFAULT true,
	"discord_alerts_enabled" boolean DEFAULT true,
	"last_alert_sent" text,
	"alert_count" integer DEFAULT 0
);
--> statement-breakpoint
CREATE INDEX "IDX_session_expire" ON "sessions" USING btree ("expire");