import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ThemeToggle } from "@/components/theme-toggle";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Skeleton } from "@/components/ui/skeleton";
import { Link, useLocation } from "wouter";
import { useQuery } from "@tanstack/react-query";
import type { TradeIdea } from "@shared/schema";
import { useAuth } from "@/hooks/useAuth";
import { 
  TrendingUp, 
  Brain, 
  Calculator, 
  Bell, 
  BarChart3, 
  Shield,
  Sparkles,
  Target,
  Zap,
  Check,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  Award,
  CheckCircle2,
  Upload,
  Clock,
  LineChart,
  FileText,
  Twitter,
  Linkedin,
  Github,
  Activity
} from "lucide-react";
import { useState, useEffect } from "react";
import { QuantEdgeLogo, QuantEdgeIcon } from "@/components/quantedge-logo";
import quantEdgeLogoUrl from "@assets/image (1)_1761160822785.png";

interface AssetTypeStats {
  assetType: string;
  totalIdeas: number;
  wonIdeas: number;
  lostIdeas: number;
  winRate: number;
  avgPercentGain: number;
}

interface PerformanceStatsResponse {
  overall: {
    totalIdeas: number;
    openIdeas: number;
    winRate: number;
    avgPercentGain: number;
  };
  byAssetType?: AssetTypeStats[];
}

export default function Landing() {
  const [, setLocation] = useLocation();
  const [carouselIndex, setCarouselIndex] = useState(0);
  const [billingPeriod, setBillingPeriod] = useState<'monthly' | 'yearly'>('monthly');
  const { isAuthenticated } = useAuth();

  const { data: perfStats, isLoading: statsLoading } = useQuery<PerformanceStatsResponse>({
    queryKey: ['/api/performance/stats'],
  });

  const { data: allIdeas, isLoading: ideasLoading } = useQuery<TradeIdea[]>({
    queryKey: ['/api/trade-ideas'],
  });

  const recentTrades = (allIdeas || [])
    .filter(idea => idea.outcomeStatus && ['hit_target', 'hit_stop', 'expired'].includes(idea.outcomeStatus))
    .sort((a, b) => {
      const dateA = a.timestamp ? new Date(a.timestamp).getTime() : 0;
      const dateB = b.timestamp ? new Date(b.timestamp).getTime() : 0;
      return dateB - dateA;
    })
    .slice(0, 5);

  useEffect(() => {
    if (carouselIndex >= recentTrades.length) {
      setCarouselIndex(0);
    }
  }, [recentTrades.length, carouselIndex]);

  const activeTrade = recentTrades.length > 0 && carouselIndex < recentTrades.length
    ? recentTrades[carouselIndex]
    : null;

  const nextTrade = () => {
    if (recentTrades.length === 0) return;
    setCarouselIndex((prev) => (prev + 1) % recentTrades.length);
  };

  const prevTrade = () => {
    if (recentTrades.length === 0) return;
    setCarouselIndex((prev) => (prev - 1 + recentTrades.length) % recentTrades.length);
  };

  const scrollToSection = (id: string) => {
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  };

  const features = [
    {
      icon: Brain,
      title: "Engine 1: AI Analysis",
      description: "Multi-provider AI (Claude, GPT, Gemini) for fundamental analysis, news catalysts, and comprehensive market insights. Generates context-aware trade ideas."
    },
    {
      icon: Calculator,
      title: "Engine 2: Quantitative Signals",
      description: "Research-backed quantitative engine using RSI(2), VWAP, volume spike detection, and pattern validation. Targets 55-65% live win rate with data-driven precision."
    },
    {
      icon: Sparkles,
      title: "Hybrid Decision System",
      description: "Both engines work together: Quant finds technical setups, AI validates fundamental strength. Get the best of both—mechanical precision plus market context."
    },
    {
      icon: Upload,
      title: "Chart Pattern Recognition",
      description: "Upload any trading chart and get instant AI analysis with technical pattern detection, support/resistance levels, and precise entry/exit zones."
    },
    {
      icon: Bell,
      title: "Instant Alerts",
      description: "Get instant Discord notifications for new trade ideas from both engines with complete entry, target, stop-loss, and probability estimates."
    },
    {
      icon: Shield,
      title: "Risk Management",
      description: "Built-in position sizing with 3.5% stock stops, 5% crypto stops, 2:1 risk-reward ratios, and complete trade validation guardrails."
    }
  ];

  const steps = [
    {
      number: "01",
      title: "Browse Ideas",
      description: "Explore trade ideas generated by our quantitative engine and AI analysis—or upload your own chart for instant analysis.",
      icon: Activity
    },
    {
      number: "02",
      title: "Get Alerts",
      description: "Receive instant Discord notifications for new opportunities with full entry, target, and stop-loss details.",
      icon: Bell
    },
    {
      number: "03",
      title: "Track Results",
      description: "Every trade is tracked automatically. See real win rates, P/L, and performance over time.",
      icon: BarChart3
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Sticky Navbar */}
      <header className="fixed top-0 left-0 right-0 z-50 glass-card border-b border-white/10" data-testid="navbar">
        <div className="container mx-auto px-6">
          <div className="flex items-center justify-between h-16 gap-4">
            {/* Left: Logo */}
            <Link href="/" className="flex-shrink-0" data-testid="link-logo">
              <img src={quantEdgeLogoUrl} alt="QuantEdge" className="h-12 w-12 object-contain" />
            </Link>

            {/* Center: Nav Links */}
            <nav className="hidden md:flex items-center gap-6">
              <button 
                onClick={() => scrollToSection('features')} 
                className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                data-testid="link-features"
              >
                Features
              </button>
              <Link 
                href="/chart-database" 
                className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                data-testid="link-chart-database"
              >
                Chart Database
              </Link>
              <button 
                onClick={() => scrollToSection('recent-performance')} 
                className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                data-testid="link-recent-performance"
              >
                Performance
              </button>
              <Link 
                href="/academy" 
                className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                data-testid="link-academy"
              >
                Academy
              </Link>
              <Link 
                href="/blog" 
                className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                data-testid="link-blog"
              >
                Blog
              </Link>
            </nav>

            {/* Right: Theme Toggle + Auth Buttons */}
            <div className="flex items-center gap-2">
              <ThemeToggle />
              {isAuthenticated ? (
                <Button onClick={() => setLocation('/home')} data-testid="button-dashboard">
                  Dashboard
                </Button>
              ) : (
                <>
                  <Button 
                    variant="outline" 
                    onClick={() => setLocation('/login')}
                    className="hidden sm:inline-flex"
                    data-testid="button-login"
                  >
                    Login
                  </Button>
                  <Button 
                    onClick={() => setLocation('/signup')}
                    data-testid="button-signup"
                  >
                    Sign Up
                  </Button>
                </>
              )}
            </div>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative pt-24 pb-16 md:pt-32 md:pb-24 overflow-hidden">
        {/* Clean Gradient Background */}
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-background to-accent/5" />
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary/10 via-transparent to-transparent" />
        
        <div className="container relative mx-auto px-6">
          <div className="max-w-4xl mx-auto text-center">
            {/* Research Platform Badge */}
            <div className="flex justify-center mb-6">
              <Badge variant="secondary" className="px-4 py-2 text-sm" data-testid="badge-research-platform">
                <FileText className="h-4 w-4 mr-2 text-amber-500" />
                Dual-Engine Research Platform
              </Badge>
            </div>

            {/* Logo */}
            <div className="flex justify-center mb-8">
              <img 
                src={quantEdgeLogoUrl} 
                alt="QuantEdge Research" 
                className="h-40 w-40 md:h-48 md:w-48 object-contain drop-shadow-lg hover:drop-shadow-xl transition-all"
              />
            </div>

            {/* Headline */}
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 leading-tight" data-testid="text-hero-headline">
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-amber-500 to-primary">2 Engines. 1 Edge.</span>
            </h1>

            {/* Subheadline */}
            <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-6" data-testid="text-hero-subheadline">
              AI Analysis + Quantitative Signals working together. Real trade ideas with entry, exit, stops, and risk calculations—for research, not advice.
            </p>

            {/* Validated Stats */}
            <div className="flex justify-center mb-10">
              <div className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-primary/10 border border-primary/20">
                <TrendingUp className="h-5 w-5 text-green-500" />
                <span className="text-lg font-semibold">
                  {statsLoading ? (
                    <Skeleton className="h-5 w-24 inline-block" />
                  ) : perfStats?.overall?.totalIdeas ? (
                    `${perfStats.overall.totalIdeas.toLocaleString()}+ Trade Ideas Generated`
                  ) : (
                    "Real Performance Data"
                  )}
                </span>
              </div>
            </div>

            {/* CTA Buttons */}
            <div className="flex flex-wrap justify-center gap-4">
              <Button 
                size="lg"
                variant="glass"
                onClick={() => setLocation('/chart-analysis')}
                data-testid="button-start-analyzing"
              >
                <Upload className="h-5 w-5 mr-2" />
                Start Analyzing
              </Button>
              <Button 
                size="lg"
                variant="glass-secondary"
                onClick={() => scrollToSection('pricing')}
                data-testid="button-view-pricing"
              >
                View Pricing
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Platform Stats */}
      <section className="border-y glass-card py-12">
        <div className="container mx-auto px-6">
          <div className="grid grid-cols-3 gap-6 max-w-3xl mx-auto">
            <div className="text-center" data-testid="stat-total-ideas">
              <div className="text-2xl md:text-3xl font-bold text-cyan-400 mb-1">
                {statsLoading ? (
                  <Skeleton className="h-8 w-16 mx-auto" />
                ) : perfStats?.overall?.totalIdeas ? (
                  `${perfStats.overall.totalIdeas.toLocaleString()}+`
                ) : (
                  "—"
                )}
              </div>
              <div className="text-xs md:text-sm text-muted-foreground">Ideas Tracked</div>
            </div>
            <div className="text-center" data-testid="stat-target">
              <div className="text-2xl md:text-3xl font-bold text-amber-500 mb-1">
                55-65%
              </div>
              <div className="text-xs md:text-sm text-muted-foreground">Target Win Rate</div>
            </div>
            <div className="text-center" data-testid="stat-rr-ratio">
              <div className="text-2xl md:text-3xl font-bold text-green-400 mb-1">
                2:1
              </div>
              <div className="text-xs md:text-sm text-muted-foreground">Min R:R Ratio</div>
            </div>
          </div>
          <p className="text-center text-xs text-muted-foreground mt-4">
            Win rate based on backtested research. Past performance does not guarantee future results.
          </p>
        </div>
      </section>

      {/* Dual Engine Showcase */}
      <section className="py-16 md:py-24 bg-gradient-to-b from-transparent via-primary/5 to-transparent">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4">
              <Brain className="h-3 w-3 mr-1" />
              How The Edge Works
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-amber-500 to-cyan-400">
                2 Engines. 1 Platform.
              </span>
              <br />
              Precision + Context
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Watch real market data flow through two independent analysis engines working in parallel
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto mb-12">
            {/* Engine 1: AI */}
            <div className="relative group">
              <div className="absolute -inset-1 bg-gradient-to-r from-cyan-500 to-blue-500 rounded-xl blur opacity-25 group-hover:opacity-75 transition duration-1000 group-hover:duration-200" />
              <div className="relative overflow-hidden rounded-xl glass-card p-8 border-l-2 border-l-cyan-400">
                <div className="flex items-center gap-3 mb-4">
                  <div className="p-3 rounded-lg bg-cyan-500/10">
                    <Brain className="h-6 w-6 text-cyan-400" />
                  </div>
                  <h3 className="text-xl font-bold">Engine 1: AI Analysis</h3>
                </div>
                <p className="text-muted-foreground mb-6">
                  Claude, GPT, and Gemini work together to analyze market fundamentals, news catalysts, and macro context.
                </p>
                <ul className="space-y-2 text-sm">
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-cyan-400" />
                    <span>Fundamental Analysis</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-cyan-400" />
                    <span>News & Catalyst Integration</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-cyan-400" />
                    <span>Market Context</span>
                  </li>
                </ul>
              </div>
            </div>

            {/* Engine 2: Quant */}
            <div className="relative group">
              <div className="absolute -inset-1 bg-gradient-to-r from-amber-500 to-green-500 rounded-xl blur opacity-25 group-hover:opacity-75 transition duration-1000 group-hover:duration-200" />
              <div className="relative overflow-hidden rounded-xl glass-card p-8 border-l-2 border-l-green-400">
                <div className="flex items-center gap-3 mb-4">
                  <div className="p-3 rounded-lg bg-green-500/10">
                    <Calculator className="h-6 w-6 text-green-400" />
                  </div>
                  <h3 className="text-xl font-bold">Engine 2: Quantitative</h3>
                </div>
                <p className="text-muted-foreground mb-6">
                  RSI(2), VWAP, volume spikes, and pattern validation create mechanical, reproducible signals.
                </p>
                <ul className="space-y-2 text-sm">
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-400" />
                    <span>Mean Reversion Signals</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-400" />
                    <span>Institutional Flow Detection</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-400" />
                    <span>55-65% Target Win Rate</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          {/* Hybrid Result */}
          <div className="text-center">
            <div className="inline-flex items-center gap-4 px-8 py-4 rounded-xl glass-card border-l-2 border-l-cyan-400">
              <Brain className="h-5 w-5 text-cyan-400" />
              <span className="text-sm font-medium">+</span>
              <Calculator className="h-5 w-5 text-green-400" />
              <span className="text-sm font-medium">=</span>
              <div>
                <p className="text-sm font-semibold text-foreground">Precision + Context</p>
                <p className="text-xs text-muted-foreground">Best of both worlds</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-16 md:py-24" id="how-it-works">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4">
              <Zap className="h-3 w-3 mr-1" />
              Simple Process
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              How It Works
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Discover opportunities, stay informed, and track your edge
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {steps.map((step, idx) => {
              const Icon = step.icon;
              return (
                <div key={step.number} className="relative overflow-hidden rounded-xl glass-card p-8 text-center" data-testid={`card-step-${idx + 1}`}>
                  <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/5 via-transparent to-blue-500/5" />
                  <div className="relative z-10">
                    <div className="h-20 w-20 rounded-full bg-cyan-500/10 border-2 border-cyan-400/20 flex items-center justify-center mx-auto mb-6">
                      <span className="text-3xl font-bold text-cyan-400">{step.number}</span>
                    </div>
                    <div className="h-12 w-12 rounded-xl bg-muted flex items-center justify-center mx-auto mb-4">
                      <Icon className="h-6 w-6 text-cyan-400" />
                    </div>
                    <h3 className="text-xl font-bold mb-3">{step.title}</h3>
                    <p className="text-sm text-muted-foreground">{step.description}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-16 md:py-24 bg-gradient-to-b from-transparent via-primary/5 to-transparent" id="features">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4">
              <Sparkles className="h-3 w-3 mr-1" />
              Platform Features
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Everything You Need
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Professional-grade tools for discovering and analyzing trading opportunities
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
            {features.map((feature, idx) => {
              const Icon = feature.icon;
              return (
                <div key={idx} className="overflow-hidden rounded-xl glass-card p-6 hover-elevate" data-testid={`card-feature-${idx}`}>
                  <div className="h-12 w-12 rounded-xl bg-cyan-500/10 flex items-center justify-center mb-4">
                    <Icon className="h-6 w-6 text-cyan-400" />
                  </div>
                  <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground mb-4">{feature.description}</p>
                  <button 
                    className="text-sm text-cyan-400 hover:underline"
                    onClick={() => scrollToSection('pricing')}
                    data-testid={`link-learn-more-${idx}`}
                  >
                    Learn more →
                  </button>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* How Our Signals Are Generated */}
      <section className="py-16 md:py-24" id="transparency">
        <div className="container mx-auto px-6">
          <div className="text-center mb-12">
            <Badge variant="secondary" className="mb-4">
              <Target className="h-3 w-3 mr-1" />
              Transparency
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              How Our Signals Are Generated
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Our dual-engine approach combines proven quantitative methods with AI-powered analysis
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            <Card data-testid="card-transparency-quant">
              <CardContent className="p-6">
                <div className="h-12 w-12 rounded-xl bg-cyan-500/10 flex items-center justify-center mb-4">
                  <Calculator className="h-6 w-6 text-cyan-400" />
                </div>
                <h3 className="text-lg font-semibold mb-3">Quantitative Engine</h3>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-cyan-400 mt-0.5 flex-shrink-0" />
                    RSI(2) mean reversion with 200-day MA filter
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-cyan-400 mt-0.5 flex-shrink-0" />
                    VWAP institutional flow analysis
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-cyan-400 mt-0.5 flex-shrink-0" />
                    Volume spike detection
                  </li>
                </ul>
              </CardContent>
            </Card>

            <Card data-testid="card-transparency-ai">
              <CardContent className="p-6">
                <div className="h-12 w-12 rounded-xl bg-amber-500/10 flex items-center justify-center mb-4">
                  <Brain className="h-6 w-6 text-amber-400" />
                </div>
                <h3 className="text-lg font-semibold mb-3">AI Analysis</h3>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-amber-400 mt-0.5 flex-shrink-0" />
                    Multi-provider LLMs (Claude, GPT, Gemini)
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-amber-400 mt-0.5 flex-shrink-0" />
                    Market context and sentiment analysis
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-amber-400 mt-0.5 flex-shrink-0" />
                    Fundamentals and news integration
                  </li>
                </ul>
              </CardContent>
            </Card>

            <Card data-testid="card-transparency-risk">
              <CardContent className="p-6">
                <div className="h-12 w-12 rounded-xl bg-green-500/10 flex items-center justify-center mb-4">
                  <Shield className="h-6 w-6 text-green-500" />
                </div>
                <h3 className="text-lg font-semibold mb-3">Risk Controls</h3>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-green-500 mt-0.5 flex-shrink-0" />
                    Entry price with precise levels
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-green-500 mt-0.5 flex-shrink-0" />
                    Target and stop-loss on every trade
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-green-500 mt-0.5 flex-shrink-0" />
                    Risk/reward ratio calculation
                  </li>
                </ul>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Recent Performance */}
      <section className="py-16 md:py-24" id="recent-performance">
        <div className="container mx-auto px-6">
          <div className="text-center mb-12">
            <Badge variant="secondary" className="mb-4">
              <Activity className="h-3 w-3 mr-1" />
              Transparent Tracking
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Recent Performance
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              All trade ideas are tracked from entry to exit. Results include both wins and losses.
            </p>
          </div>

          {ideasLoading ? (
            <div className="max-w-4xl mx-auto">
              <Skeleton className="h-64 w-full rounded-2xl" data-testid="skeleton-recent-trades" />
            </div>
          ) : activeTrade ? (
            <div className="max-w-4xl mx-auto relative">
              <div className="flex items-center justify-between gap-4">
                <Button
                  variant="outline"
                  size="icon"
                  onClick={prevTrade}
                  disabled={recentTrades.length <= 1}
                  data-testid="button-carousel-prev"
                >
                  <ChevronLeft className="h-5 w-5" />
                </Button>

                <Card className="flex-1" data-testid={`card-recent-trade-${carouselIndex}`}>
                  <CardContent className="p-8 md:p-10">
                    <div className="flex items-start justify-between gap-4 mb-6">
                      <div className="flex items-center gap-3">
                        <div className={`h-14 w-14 rounded-2xl flex items-center justify-center ${
                          activeTrade.outcomeStatus === 'hit_target' 
                            ? 'bg-green-500/10' 
                            : 'bg-red-500/10'
                        }`}>
                          <TrendingUp className={`h-7 w-7 ${
                            activeTrade.outcomeStatus === 'hit_target' 
                              ? 'text-green-500' 
                              : 'text-red-500'
                          }`} />
                        </div>
                        <div>
                          <h3 className="text-2xl font-bold mb-1" data-testid="text-trade-symbol">
                            {activeTrade.symbol}
                          </h3>
                          <Badge 
                            variant={activeTrade.direction === 'long' ? 'default' : 'secondary'}
                            data-testid="badge-trade-direction"
                          >
                            {activeTrade.direction.toUpperCase()}
                          </Badge>
                        </div>
                      </div>
                      <Badge 
                        variant={activeTrade.outcomeStatus === 'hit_target' ? 'default' : 'destructive'}
                        data-testid="badge-trade-outcome"
                      >
                        {activeTrade.outcomeStatus === 'hit_target' ? 'Win' : 'Loss'}
                      </Badge>
                    </div>

                    <div className="grid grid-cols-2 gap-6 mb-6">
                      <div>
                        <p className="text-sm text-muted-foreground mb-1">Entry Price</p>
                        <p className="text-xl font-bold" data-testid="text-trade-entry">
                          ${activeTrade.entryPrice?.toFixed(2) || 'N/A'}
                        </p>
                      </div>
                      <div>
                        <p className="text-sm text-muted-foreground mb-1">Exit Price</p>
                        <p className="text-xl font-bold" data-testid="text-trade-exit">
                          ${activeTrade.exitPrice?.toFixed(2) || 'N/A'}
                        </p>
                      </div>
                    </div>

                    <div className={`rounded-xl p-6 text-center ${
                      (activeTrade.percentGain || 0) >= 0 
                        ? 'bg-green-500/10' 
                        : 'bg-red-500/10'
                    }`}>
                      <p className="text-sm text-muted-foreground mb-2">Result</p>
                      <p className={`text-5xl font-bold ${
                        (activeTrade.percentGain || 0) >= 0 
                          ? 'text-green-500' 
                          : 'text-red-500'
                      }`} data-testid="text-trade-result">
                        {(activeTrade.percentGain || 0) >= 0 ? '+' : ''}{activeTrade.percentGain?.toFixed(1) || '0.0'}%
                      </p>
                    </div>
                  </CardContent>
                </Card>

                <Button
                  variant="outline"
                  size="icon"
                  onClick={nextTrade}
                  disabled={recentTrades.length <= 1}
                  data-testid="button-carousel-next"
                >
                  <ChevronRight className="h-5 w-5" />
                </Button>
              </div>

              {recentTrades.length > 1 && (
                <div className="flex justify-center gap-2 mt-6">
                  {recentTrades.map((_, idx) => (
                    <button
                      key={idx}
                      onClick={() => setCarouselIndex(idx)}
                      className={`h-2 rounded-full transition-all ${
                        idx === carouselIndex ? 'w-8 bg-primary' : 'w-2 bg-muted'
                      }`}
                      data-testid={`button-carousel-indicator-${idx}`}
                    />
                  ))}
                </div>
              )}
            </div>
          ) : (
            <div className="max-w-2xl mx-auto">
              <Card>
                <CardContent className="p-12 text-center">
                  <BarChart3 className="h-16 w-16 text-muted-foreground mx-auto mb-4 opacity-50" />
                  <h3 className="text-xl font-semibold mb-2">Performance Tracking</h3>
                  <p className="text-muted-foreground mb-6">
                    All trade ideas are tracked from entry to exit. View real results—both wins and losses.
                  </p>
                  <Button onClick={() => setLocation('/trade-desk')} data-testid="button-view-trades-cta">
                    <ArrowRight className="h-4 w-4 mr-2" />
                    View Trade Ideas
                  </Button>
                </CardContent>
              </Card>
            </div>
          )}
        </div>
      </section>

      {/* Pricing Section */}
      <section className="py-16 md:py-24 bg-muted/30" id="pricing">
        <div className="container mx-auto px-6">
          <div className="text-center mb-12">
            <Badge variant="secondary" className="mb-4">
              <LineChart className="h-3 w-3 mr-1" />
              Pricing Plans
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Choose Your Plan
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto mb-8">
              Start free and upgrade as you grow
            </p>
            
            {/* Billing Toggle */}
            <div className="flex items-center justify-center gap-4" data-testid="billing-toggle">
              <span className={`text-sm font-medium ${billingPeriod === 'monthly' ? 'text-foreground' : 'text-muted-foreground'}`}>
                Monthly
              </span>
              <button
                onClick={() => setBillingPeriod(billingPeriod === 'monthly' ? 'yearly' : 'monthly')}
                className={`relative inline-flex h-7 w-14 items-center rounded-full transition-colors ${
                  billingPeriod === 'yearly' ? 'bg-primary' : 'bg-muted'
                }`}
                data-testid="button-billing-toggle"
              >
                <span
                  className={`inline-block h-5 w-5 transform rounded-full bg-white shadow-md transition-transform ${
                    billingPeriod === 'yearly' ? 'translate-x-8' : 'translate-x-1'
                  }`}
                />
              </button>
              <div className="flex items-center gap-2">
                <span className={`text-sm font-medium ${billingPeriod === 'yearly' ? 'text-foreground' : 'text-muted-foreground'}`}>
                  Yearly
                </span>
                <Badge variant="secondary" className="text-xs bg-green-500/10 text-green-500 border-green-500/20">
                  Save 17%
                </Badge>
              </div>
            </div>
          </div>

          <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            {/* Free Tier */}
            <Card data-testid="card-pricing-free">
              <CardContent className="p-8 flex flex-col h-full">
                <div className="mb-6">
                  <h3 className="text-xl font-bold mb-2">Free</h3>
                  <div className="flex items-baseline gap-1 mb-2">
                    <span className="text-4xl font-bold">$0</span>
                    <span className="text-muted-foreground">/month</span>
                  </div>
                  <p className="text-sm text-muted-foreground">Preview the platform</p>
                </div>
                
                <ul className="space-y-3 mb-8 flex-1">
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span className="text-sm">5 trade ideas per day</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Delayed market data (15min)</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span className="text-sm">7-day performance history</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Stocks & crypto only</span>
                  </li>
                </ul>
                
                <Button 
                  variant="outline" 
                  className="w-full"
                  onClick={() => setLocation('/signup')}
                  data-testid="button-pricing-free"
                >
                  Get Started Free
                </Button>
              </CardContent>
            </Card>

            {/* Advanced Tier */}
            <Card className="relative border-primary" data-testid="card-pricing-advanced">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                <Badge>Most Popular</Badge>
              </div>
              <CardContent className="p-8 flex flex-col h-full">
                <div className="mb-6">
                  <h3 className="text-xl font-bold mb-2">Advanced</h3>
                  <div className="flex items-baseline gap-1 mb-2">
                    <span className="text-4xl font-bold text-primary">
                      ${billingPeriod === 'monthly' ? '39' : '33'}
                    </span>
                    <span className="text-muted-foreground">/month</span>
                  </div>
                  {billingPeriod === 'yearly' && (
                    <p className="text-xs text-green-500">Billed $390/year (save $78)</p>
                  )}
                  <p className="text-sm text-muted-foreground">Full stock & crypto access</p>
                </div>
                
                <ul className="space-y-3 mb-8 flex-1">
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm font-medium">Everything in Free</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Unlimited trade ideas</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Real-time market data</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Unlimited chart analyses</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Unlimited AI generations</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Full performance history</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Discord alerts</span>
                  </li>
                </ul>
                
                <Button 
                  variant="glass"
                  className="w-full"
                  onClick={() => setLocation('/signup')}
                  data-testid="button-pricing-advanced"
                >
                  <Sparkles className="h-4 w-4 mr-2" />
                  Get Advanced
                </Button>
              </CardContent>
            </Card>

            {/* Pro Tier - Coming Soon */}
            <Card className="relative border-amber-500/30 bg-amber-500/5" data-testid="card-pricing-pro">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                <Badge variant="secondary" className="bg-amber-500/10 text-amber-600 border-amber-500/20">
                  <Clock className="h-3 w-3 mr-1" />
                  Coming Soon
                </Badge>
              </div>
              <CardContent className="p-8 flex flex-col h-full">
                <div className="mb-6">
                  <h3 className="text-xl font-bold mb-2">Pro</h3>
                  <div className="flex items-baseline gap-1 mb-2">
                    <span className="text-4xl font-bold text-amber-600">$79</span>
                    <span className="text-muted-foreground">/month</span>
                  </div>
                  <p className="text-sm text-muted-foreground">Institutional-grade tools</p>
                </div>
                
                <ul className="space-y-3 mb-8 flex-1">
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-amber-600 mt-0.5 flex-shrink-0" />
                    <span className="text-sm font-medium">Everything in Advanced</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Clock className="h-5 w-5 text-amber-500/60 mt-0.5 flex-shrink-0" />
                    <span className="text-sm text-muted-foreground">Futures trading (NQ, ES, GC)</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Clock className="h-5 w-5 text-amber-500/60 mt-0.5 flex-shrink-0" />
                    <span className="text-sm text-muted-foreground">REST API access</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Clock className="h-5 w-5 text-amber-500/60 mt-0.5 flex-shrink-0" />
                    <span className="text-sm text-muted-foreground">White-label PDF reports</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Clock className="h-5 w-5 text-amber-500/60 mt-0.5 flex-shrink-0" />
                    <span className="text-sm text-muted-foreground">Backtesting module</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Clock className="h-5 w-5 text-amber-500/60 mt-0.5 flex-shrink-0" />
                    <span className="text-sm text-muted-foreground">Custom webhooks</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Clock className="h-5 w-5 text-amber-500/60 mt-0.5 flex-shrink-0" />
                    <span className="text-sm text-muted-foreground">Priority idea generation</span>
                  </li>
                </ul>
                
                <Button 
                  variant="glass-secondary"
                  className="w-full"
                  data-testid="button-pricing-pro"
                >
                  <Clock className="h-4 w-4 mr-2" />
                  Join Waitlist
                </Button>
              </CardContent>
            </Card>

          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-16 md:py-24" id="faq">
        <div className="container mx-auto px-6">
          <div className="text-center mb-12">
            <Badge variant="secondary" className="mb-4">
              <Activity className="h-3 w-3 mr-1" />
              FAQ
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Frequently Asked Questions
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Everything you need to know about QuantEdge
            </p>
          </div>

          <div className="max-w-3xl mx-auto">
            <Accordion type="single" collapsible className="space-y-3">
              <AccordionItem value="accuracy" className="border rounded-xl px-6" data-testid="accordion-faq-accuracy">
                <AccordionTrigger className="text-left font-medium hover:no-underline py-4" data-testid="trigger-faq-accuracy">
                  How accurate are the trade signals?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-4" data-testid="content-faq-accuracy">
                  Our quantitative engine uses research-backed strategies targeting 55-65% win rate in live trading. 
                  Every trade is tracked transparently with actual win/loss results. Past performance does not guarantee future results.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="trading-styles" className="border rounded-xl px-6" data-testid="accordion-faq-styles">
                <AccordionTrigger className="text-left font-medium hover:no-underline py-4" data-testid="trigger-faq-styles">
                  Can I use QuantEdge for different trading styles?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-4" data-testid="content-faq-styles">
                  Yes! QuantEdge supports day trading, swing trading, and position trading. 
                  Each trade idea includes holding period recommendations optimized for the opportunity.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="markets" className="border rounded-xl px-6" data-testid="accordion-faq-markets">
                <AccordionTrigger className="text-left font-medium hover:no-underline py-4" data-testid="trigger-faq-markets">
                  What markets does QuantEdge cover?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-4" data-testid="content-faq-markets">
                  QuantEdge analyzes US equities, options, cryptocurrencies, and futures contracts. 
                  Real-time data is sourced from Yahoo Finance, Alpha Vantage, Tradier, and CoinGecko.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="dual-engine" className="border rounded-xl px-6" data-testid="accordion-faq-dual-engine">
                <AccordionTrigger className="text-left font-medium hover:no-underline py-4" data-testid="trigger-faq-dual-engine">
                  How does the dual-engine system work?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-4" data-testid="content-faq-dual-engine">
                  Our AI Engine uses multi-provider LLMs for contextual insights. The Quantitative Engine runs research-backed technical strategies. 
                  When both engines agree, win rates historically increase by 18%.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="beginners" className="border rounded-xl px-6" data-testid="accordion-faq-beginners">
                <AccordionTrigger className="text-left font-medium hover:no-underline py-4" data-testid="trigger-faq-beginners">
                  Is QuantEdge suitable for beginners?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-4" data-testid="content-faq-beginners">
                  QuantEdge is designed as an educational research platform. Every trade idea includes explainability features 
                  to help you understand the reasoning. We recommend paper trading while learning.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="premium" className="border rounded-xl px-6" data-testid="accordion-faq-premium">
                <AccordionTrigger className="text-left font-medium hover:no-underline py-4" data-testid="trigger-faq-premium">
                  What's the difference between the plans?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-4" data-testid="content-faq-premium">
                  <strong>Free</strong> gives you 5 trade ideas per day with delayed market data to preview the platform. 
                  <strong>Advanced</strong> ($39/mo) unlocks unlimited trade ideas, real-time data, chart analysis, Discord alerts, and full performance history.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-6">
          <div className="relative overflow-hidden rounded-xl glass-card p-12 text-center">
            <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/10 via-transparent to-blue-500/10" />
            <div className="relative z-10">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                Ready to Trade with Precision?
              </h2>
              <p className="text-muted-foreground max-w-2xl mx-auto mb-8">
                Research platform for self-directed traders. Paper trade first, risk second.
              </p>
              <div className="flex flex-wrap justify-center gap-4">
                <Button size="lg" variant="glass" onClick={() => setLocation('/signup')} data-testid="button-cta-signup">
                  Get Started Free
                  <ArrowRight className="h-5 w-5 ml-2" />
                </Button>
                <Button size="lg" variant="glass-secondary" onClick={() => setLocation('/chart-analysis')} data-testid="button-cta-demo">
                  Try Chart Analysis
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Professional Footer */}
      <footer className="border-t py-12 md:py-16" data-testid="footer">
        <div className="container mx-auto px-6">
          <div className="grid md:grid-cols-4 gap-8 mb-12">
            {/* Brand Column */}
            <div className="md:col-span-1">
              <div className="flex items-center gap-2 mb-4">
                <img src={quantEdgeLogoUrl} alt="QuantEdge" className="h-8 w-8 object-contain" />
                <span className="font-bold text-lg">QuantEdge</span>
              </div>
              <p className="text-sm text-muted-foreground mb-4">
                Research tools for self-directed traders. Education, not advice.
              </p>
              <div className="flex items-center gap-3">
                <Button variant="ghost" size="icon" data-testid="link-social-twitter">
                  <Twitter className="h-4 w-4" />
                </Button>
                <Button variant="ghost" size="icon" data-testid="link-social-linkedin">
                  <Linkedin className="h-4 w-4" />
                </Button>
                <Button variant="ghost" size="icon" data-testid="link-social-github">
                  <Github className="h-4 w-4" />
                </Button>
              </div>
            </div>

            {/* Product Column */}
            <div>
              <h4 className="font-semibold mb-4">Product</h4>
              <ul className="space-y-3">
                <li>
                  <button 
                    onClick={() => scrollToSection('features')} 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-features"
                  >
                    Features
                  </button>
                </li>
                <li>
                  <Link 
                    href="/chart-database" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-chart-database"
                  >
                    Chart Database
                  </Link>
                </li>
                <li>
                  <Link 
                    href="/trade-desk" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-dashboard"
                  >
                    Dashboard
                  </Link>
                </li>
                <li>
                  <button 
                    onClick={() => scrollToSection('pricing')} 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-pricing"
                  >
                    Pricing
                  </button>
                </li>
              </ul>
            </div>

            {/* Resources Column */}
            <div>
              <h4 className="font-semibold mb-4">Resources</h4>
              <ul className="space-y-3">
                <li>
                  <Link 
                    href="/academy" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-academy"
                  >
                    Academy
                  </Link>
                </li>
                <li>
                  <Link 
                    href="/blog" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-blog"
                  >
                    Blog
                  </Link>
                </li>
                <li>
                  <button 
                    onClick={() => scrollToSection('recent-performance')} 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-performance"
                  >
                    Performance
                  </button>
                </li>
                <li>
                  <Link 
                    href="/terms" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-terms"
                  >
                    Terms of Service
                  </Link>
                </li>
                <li>
                  <Link 
                    href="/privacy" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-privacy"
                  >
                    Privacy Policy
                  </Link>
                </li>
              </ul>
            </div>

            {/* Get Started Column */}
            <div>
              <h4 className="font-semibold mb-4">Get Started</h4>
              <p className="text-sm text-muted-foreground mb-4">
                Start analyzing charts with AI precision today.
              </p>
              <Button onClick={() => setLocation('/signup')} className="w-full" data-testid="footer-button-signup">
                Create Free Account
              </Button>
            </div>
          </div>

          {/* Risk Disclaimer */}
          <div className="border-t pt-8 mb-6">
            <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-4 text-center">
              <p className="text-sm font-medium text-destructive mb-1">
                NOT FINANCIAL ADVICE
              </p>
              <p className="text-xs text-muted-foreground">
                QuantEdge is an educational research platform. Trading involves substantial risk of loss. 
                Past performance does not guarantee future results. You could lose your entire investment.
              </p>
            </div>
          </div>

          {/* Bottom Bar */}
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <p className="text-sm text-muted-foreground">
              © {new Date().getFullYear()} QuantEdge Research. All rights reserved.
            </p>
            <p className="text-xs text-muted-foreground text-center md:text-right">
              Research platform for self-directed traders. Education, not advice.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
