import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ThemeToggle } from "@/components/theme-toggle";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Skeleton } from "@/components/ui/skeleton";
import { Link, useLocation } from "wouter";
import { useQuery } from "@tanstack/react-query";
import type { TradeIdea } from "@shared/schema";
import { useAuth } from "@/hooks/useAuth";
import { 
  TrendingUp, 
  Brain, 
  Calculator, 
  Bell, 
  BarChart3, 
  Shield,
  Sparkles,
  Target,
  Zap,
  Check,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  Award,
  CheckCircle2,
  Upload,
  Clock,
  LineChart,
  FileText,
  Twitter,
  Linkedin,
  Github,
  Activity
} from "lucide-react";
import quantEdgeLogoUrl from "@assets/image (1)_1761160822785.png";
import { useState, useEffect } from "react";

interface AssetTypeStats {
  assetType: string;
  totalIdeas: number;
  wonIdeas: number;
  lostIdeas: number;
  winRate: number;
  avgPercentGain: number;
}

interface PerformanceStatsResponse {
  overall: {
    totalIdeas: number;
    openIdeas: number;
    winRate: number;
    avgPercentGain: number;
  };
  byAssetType?: AssetTypeStats[];
}

export default function Landing() {
  const [, setLocation] = useLocation();
  const [carouselIndex, setCarouselIndex] = useState(0);
  const [billingPeriod, setBillingPeriod] = useState<'monthly' | 'yearly'>('monthly');
  const { isAuthenticated } = useAuth();

  const { data: perfStats, isLoading: statsLoading } = useQuery<PerformanceStatsResponse>({
    queryKey: ['/api/performance/stats'],
  });

  const { data: allIdeas, isLoading: ideasLoading } = useQuery<TradeIdea[]>({
    queryKey: ['/api/trade-ideas'],
  });

  const successStories = (allIdeas || [])
    .filter(idea => idea.outcomeStatus === 'hit_target' && (idea.percentGain || 0) > 10)
    .sort((a, b) => (b.percentGain || 0) - (a.percentGain || 0))
    .slice(0, 5);

  useEffect(() => {
    if (carouselIndex >= successStories.length) {
      setCarouselIndex(0);
    }
  }, [successStories.length, carouselIndex]);

  const activeStory = successStories.length > 0 && carouselIndex < successStories.length
    ? successStories[carouselIndex]
    : null;

  const nextStory = () => {
    if (successStories.length === 0) return;
    setCarouselIndex((prev) => (prev + 1) % successStories.length);
  };

  const prevStory = () => {
    if (successStories.length === 0) return;
    setCarouselIndex((prev) => (prev - 1 + successStories.length) % successStories.length);
  };

  const scrollToSection = (id: string) => {
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  };

  const features = [
    {
      icon: Upload,
      title: "Chart Pattern Recognition",
      description: "Upload any trading chart and get instant AI analysis with pattern detection and precise entry/exit points."
    },
    {
      icon: Brain,
      title: "AI-Powered Analysis",
      description: "Multi-provider AI (Claude, GPT, Gemini) generates trade ideas with comprehensive market analysis."
    },
    {
      icon: Calculator,
      title: "Quantitative Signals",
      description: "Research-backed engine using proven strategies with 75-91% historical win rates."
    },
    {
      icon: Bell,
      title: "Instant Alerts",
      description: "Get instant notifications for new trade ideas with complete details delivered to Discord."
    },
    {
      icon: BarChart3,
      title: "Real-Time Data",
      description: "Live pricing from Yahoo Finance, Alpha Vantage, and CoinGecko across all markets."
    },
    {
      icon: Shield,
      title: "Risk Management",
      description: "Built-in position sizing calculator with entry, target, stop-loss, and R:R ratio."
    }
  ];

  const steps = [
    {
      number: "01",
      title: "Browse Ideas",
      description: "Explore trade ideas generated by our quantitative engine and AI analysis—or upload your own chart for instant analysis.",
      icon: Activity
    },
    {
      number: "02",
      title: "Get Alerts",
      description: "Receive instant Discord notifications for new opportunities with full entry, target, and stop-loss details.",
      icon: Bell
    },
    {
      number: "03",
      title: "Track Results",
      description: "Every trade is tracked automatically. See real win rates, P/L, and performance over time.",
      icon: BarChart3
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Sticky Navbar */}
      <header className="fixed top-0 left-0 right-0 z-50" data-testid="navbar">
        <div className="container mx-auto px-6">
          <div className="flex items-center justify-between h-16 gap-4">
            {/* Left: Logo */}
            <Link href="/" className="flex items-center gap-2 flex-shrink-0" data-testid="link-logo">
              <img src={quantEdgeLogoUrl} alt="QuantEdge" className="h-8 w-8 object-contain" />
              <span className="font-bold text-lg hidden sm:block">QuantEdge</span>
            </Link>

            {/* Center: Nav Links */}
            <nav className="hidden md:flex items-center gap-6">
              <button 
                onClick={() => scrollToSection('features')} 
                className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                data-testid="link-features"
              >
                Features
              </button>
              <Link 
                href="/chart-database" 
                className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                data-testid="link-chart-database"
              >
                Chart Database
              </Link>
              <button 
                onClick={() => scrollToSection('success-stories')} 
                className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                data-testid="link-success-stories"
              >
                Success Stories
              </button>
              <Link 
                href="/academy" 
                className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                data-testid="link-academy"
              >
                Academy
              </Link>
              <Link 
                href="/blog" 
                className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                data-testid="link-blog"
              >
                Blog
              </Link>
            </nav>

            {/* Right: Theme Toggle + Auth Buttons */}
            <div className="flex items-center gap-2">
              <ThemeToggle />
              {isAuthenticated ? (
                <Button onClick={() => setLocation('/trade-desk')} data-testid="button-dashboard">
                  Dashboard
                </Button>
              ) : (
                <>
                  <Button 
                    variant="outline" 
                    onClick={() => setLocation('/login')}
                    className="hidden sm:inline-flex"
                    data-testid="button-login"
                  >
                    Login
                  </Button>
                  <Button 
                    onClick={() => setLocation('/signup')}
                    data-testid="button-signup"
                  >
                    Sign Up
                  </Button>
                </>
              )}
            </div>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative pt-24 pb-16 md:pt-32 md:pb-24 overflow-hidden">
        {/* Clean Gradient Background */}
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-background to-accent/5" />
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary/10 via-transparent to-transparent" />
        
        <div className="container relative mx-auto px-6">
          <div className="max-w-4xl mx-auto text-center">
            {/* Dual Engine Badge */}
            <div className="flex justify-center mb-6">
              <Badge variant="secondary" className="px-4 py-2 text-sm" data-testid="badge-dual-engine">
                <Zap className="h-4 w-4 mr-2 text-amber-500" />
                Dual-Engine Architecture: AI + Quantitative
              </Badge>
            </div>

            {/* Logo */}
            <div className="flex justify-center mb-8">
              <img 
                src={quantEdgeLogoUrl} 
                alt="QuantEdge" 
                className="h-36 w-36 md:h-44 md:w-44 object-contain drop-shadow-xl"
              />
            </div>

            {/* Headline */}
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 leading-tight" data-testid="text-hero-headline">
              Two engines. <span className="text-primary">One edge.</span>
            </h1>

            {/* Subheadline */}
            <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-6" data-testid="text-hero-subheadline">
              Quantitative signals and AI analysis working together. Stocks, options, crypto—every trade idea comes with entry, exit, and risk levels.
            </p>

            {/* Validated Stats */}
            <div className="flex justify-center mb-10">
              <div className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-primary/10 border border-primary/20">
                <TrendingUp className="h-5 w-5 text-green-500" />
                <span className="text-lg font-semibold">
                  {statsLoading ? (
                    <Skeleton className="h-5 w-24 inline-block" />
                  ) : perfStats?.overall?.totalIdeas ? (
                    `${perfStats.overall.totalIdeas.toLocaleString()}+ Validated Trades`
                  ) : (
                    "Real Performance Data"
                  )}
                </span>
              </div>
            </div>

            {/* CTA Buttons */}
            <div className="flex flex-wrap justify-center gap-4">
              <Button 
                size="lg"
                onClick={() => setLocation('/chart-analysis')}
                data-testid="button-start-analyzing"
              >
                <Upload className="h-5 w-5 mr-2" />
                Start Analyzing
              </Button>
              <Button 
                size="lg"
                variant="outline"
                onClick={() => scrollToSection('pricing')}
                data-testid="button-view-pricing"
              >
                View Pricing
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Platform Stats */}
      <section className="border-y bg-muted/30 py-12">
        <div className="container mx-auto px-6">
          <div className="grid grid-cols-3 gap-6 max-w-3xl mx-auto">
            <div className="text-center" data-testid="stat-total-ideas">
              <div className="text-2xl md:text-3xl font-bold text-primary mb-1">
                {statsLoading ? (
                  <Skeleton className="h-8 w-16 mx-auto" />
                ) : perfStats?.overall?.totalIdeas ? (
                  `${perfStats.overall.totalIdeas.toLocaleString()}+`
                ) : (
                  "—"
                )}
              </div>
              <div className="text-xs md:text-sm text-muted-foreground">Trade Ideas</div>
            </div>
            <div className="text-center" data-testid="stat-stock-win-rate">
              <div className="text-2xl md:text-3xl font-bold text-green-500 mb-1">
                {statsLoading ? (
                  <Skeleton className="h-8 w-16 mx-auto" />
                ) : (() => {
                  const stockStats = perfStats?.byAssetType?.find(a => a.assetType === 'stock');
                  return stockStats?.winRate ? `${stockStats.winRate.toFixed(0)}%` : "—";
                })()}
              </div>
              <div className="text-xs md:text-sm text-muted-foreground">Stocks Win Rate</div>
            </div>
            <div className="text-center" data-testid="stat-crypto-win-rate">
              <div className="text-2xl md:text-3xl font-bold text-amber-500 mb-1">
                {statsLoading ? (
                  <Skeleton className="h-8 w-16 mx-auto" />
                ) : (() => {
                  const cryptoStats = perfStats?.byAssetType?.find(a => a.assetType === 'crypto');
                  return cryptoStats?.winRate ? `${cryptoStats.winRate.toFixed(0)}%` : "—";
                })()}
              </div>
              <div className="text-xs md:text-sm text-muted-foreground">Crypto Win Rate</div>
            </div>
          </div>
          <p className="text-center text-xs text-muted-foreground mt-4">
            Based on validated trades with confirmed outcomes (excludes options pending proper pricing)
          </p>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-16 md:py-24" id="how-it-works">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4">
              <Zap className="h-3 w-3 mr-1" />
              Simple Process
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              How It Works
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Discover opportunities, stay informed, and track your edge
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {steps.map((step, idx) => {
              const Icon = step.icon;
              return (
                <Card key={step.number} className="relative" data-testid={`card-step-${idx + 1}`}>
                  <CardContent className="p-8 text-center">
                    {/* Large Number Circle */}
                    <div className="h-20 w-20 rounded-full bg-primary/10 border-2 border-primary/20 flex items-center justify-center mx-auto mb-6">
                      <span className="text-3xl font-bold text-primary">{step.number}</span>
                    </div>
                    
                    {/* Icon */}
                    <div className="h-12 w-12 rounded-xl bg-muted flex items-center justify-center mx-auto mb-4">
                      <Icon className="h-6 w-6 text-muted-foreground" />
                    </div>
                    
                    <h3 className="text-xl font-bold mb-3">{step.title}</h3>
                    <p className="text-sm text-muted-foreground">{step.description}</p>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-16 md:py-24 bg-muted/30" id="features">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <Badge variant="secondary" className="mb-4">
              <Sparkles className="h-3 w-3 mr-1" />
              Platform Features
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Everything You Need
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Professional-grade tools for discovering and analyzing trading opportunities
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
            {features.map((feature, idx) => {
              const Icon = feature.icon;
              return (
                <Card key={idx} className="hover-elevate" data-testid={`card-feature-${idx}`}>
                  <CardContent className="p-6">
                    <div className="h-12 w-12 rounded-xl bg-primary/10 flex items-center justify-center mb-4">
                      <Icon className="h-6 w-6 text-primary" />
                    </div>
                    <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                    <p className="text-sm text-muted-foreground mb-4">{feature.description}</p>
                    <button 
                      className="text-sm text-primary hover:underline"
                      onClick={() => scrollToSection('pricing')}
                      data-testid={`link-learn-more-${idx}`}
                    >
                      Learn more →
                    </button>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* How Our Signals Are Generated */}
      <section className="py-16 md:py-24" id="transparency">
        <div className="container mx-auto px-6">
          <div className="text-center mb-12">
            <Badge variant="secondary" className="mb-4">
              <Target className="h-3 w-3 mr-1" />
              Transparency
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              How Our Signals Are Generated
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Our dual-engine approach combines proven quantitative methods with AI-powered analysis
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            <Card data-testid="card-transparency-quant">
              <CardContent className="p-6">
                <div className="h-12 w-12 rounded-xl bg-blue-500/10 flex items-center justify-center mb-4">
                  <Calculator className="h-6 w-6 text-blue-500" />
                </div>
                <h3 className="text-lg font-semibold mb-3">Quantitative Engine</h3>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-blue-500 mt-0.5 flex-shrink-0" />
                    RSI(2) mean reversion with 200-day MA filter
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-blue-500 mt-0.5 flex-shrink-0" />
                    VWAP institutional flow analysis
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-blue-500 mt-0.5 flex-shrink-0" />
                    Volume spike detection
                  </li>
                </ul>
              </CardContent>
            </Card>

            <Card data-testid="card-transparency-ai">
              <CardContent className="p-6">
                <div className="h-12 w-12 rounded-xl bg-purple-500/10 flex items-center justify-center mb-4">
                  <Brain className="h-6 w-6 text-purple-500" />
                </div>
                <h3 className="text-lg font-semibold mb-3">AI Analysis</h3>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-purple-500 mt-0.5 flex-shrink-0" />
                    Multi-provider LLMs (Claude, GPT, Gemini)
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-purple-500 mt-0.5 flex-shrink-0" />
                    Market context and sentiment analysis
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-purple-500 mt-0.5 flex-shrink-0" />
                    Fundamentals and news integration
                  </li>
                </ul>
              </CardContent>
            </Card>

            <Card data-testid="card-transparency-risk">
              <CardContent className="p-6">
                <div className="h-12 w-12 rounded-xl bg-green-500/10 flex items-center justify-center mb-4">
                  <Shield className="h-6 w-6 text-green-500" />
                </div>
                <h3 className="text-lg font-semibold mb-3">Risk Controls</h3>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-green-500 mt-0.5 flex-shrink-0" />
                    Entry price with precise levels
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-green-500 mt-0.5 flex-shrink-0" />
                    Target and stop-loss on every trade
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-green-500 mt-0.5 flex-shrink-0" />
                    Risk/reward ratio calculation
                  </li>
                </ul>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Success Stories Carousel */}
      <section className="py-16 md:py-24" id="success-stories">
        <div className="container mx-auto px-6">
          <div className="text-center mb-12">
            <Badge variant="secondary" className="mb-4">
              <Award className="h-3 w-3 mr-1" />
              Verified Results
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Success Stories
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Real results from our platform. Every trade is tracked and verified.
            </p>
          </div>

          {ideasLoading ? (
            <div className="max-w-4xl mx-auto">
              <Skeleton className="h-64 w-full rounded-2xl" data-testid="skeleton-success-stories" />
            </div>
          ) : activeStory ? (
            <div className="max-w-4xl mx-auto relative">
              <div className="flex items-center justify-between gap-4">
                <Button
                  variant="outline"
                  size="icon"
                  onClick={prevStory}
                  disabled={successStories.length <= 1}
                  data-testid="button-carousel-prev"
                >
                  <ChevronLeft className="h-5 w-5" />
                </Button>

                <Card className="flex-1" data-testid={`card-success-story-${carouselIndex}`}>
                  <CardContent className="p-8 md:p-10">
                    <div className="flex items-start justify-between gap-4 mb-6">
                      <div className="flex items-center gap-3">
                        <div className="h-14 w-14 rounded-2xl bg-green-500/10 flex items-center justify-center">
                          <TrendingUp className="h-7 w-7 text-green-500" />
                        </div>
                        <div>
                          <h3 className="text-2xl font-bold mb-1" data-testid="text-success-symbol">
                            {activeStory.symbol}
                          </h3>
                          <Badge 
                            variant={activeStory.direction === 'long' ? 'default' : 'secondary'}
                            data-testid="badge-success-direction"
                          >
                            {activeStory.direction.toUpperCase()}
                          </Badge>
                        </div>
                      </div>
                      <div className="flex items-center gap-2 text-green-500">
                        <CheckCircle2 className="h-5 w-5" />
                        <span className="text-xs">Verified</span>
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-6 mb-6">
                      <div>
                        <p className="text-sm text-muted-foreground mb-1">Entry Price</p>
                        <p className="text-xl font-bold" data-testid="text-success-entry">
                          ${activeStory.entryPrice?.toFixed(2) || 'N/A'}
                        </p>
                      </div>
                      <div>
                        <p className="text-sm text-muted-foreground mb-1">Exit Price</p>
                        <p className="text-xl font-bold" data-testid="text-success-exit">
                          ${activeStory.exitPrice?.toFixed(2) || 'N/A'}
                        </p>
                      </div>
                    </div>

                    <div className="bg-green-500/10 rounded-xl p-6 text-center">
                      <p className="text-sm text-muted-foreground mb-2">Realized Gain</p>
                      <p className="text-5xl font-bold text-green-500" data-testid="text-success-gain">
                        +{activeStory.percentGain?.toFixed(1) || '0.0'}%
                      </p>
                    </div>
                  </CardContent>
                </Card>

                <Button
                  variant="outline"
                  size="icon"
                  onClick={nextStory}
                  disabled={successStories.length <= 1}
                  data-testid="button-carousel-next"
                >
                  <ChevronRight className="h-5 w-5" />
                </Button>
              </div>

              {successStories.length > 1 && (
                <div className="flex justify-center gap-2 mt-6">
                  {successStories.map((_, idx) => (
                    <button
                      key={idx}
                      onClick={() => setCarouselIndex(idx)}
                      className={`h-2 rounded-full transition-all ${
                        idx === carouselIndex ? 'w-8 bg-primary' : 'w-2 bg-muted'
                      }`}
                      data-testid={`button-carousel-indicator-${idx}`}
                    />
                  ))}
                </div>
              )}
            </div>
          ) : (
            <div className="max-w-2xl mx-auto">
              <Card>
                <CardContent className="p-12 text-center">
                  <Award className="h-16 w-16 text-muted-foreground mx-auto mb-4 opacity-50" />
                  <h3 className="text-xl font-semibold mb-2">Building Success Stories</h3>
                  <p className="text-muted-foreground mb-6">
                    We're generating winning trades every day. Check back soon!
                  </p>
                  <Button onClick={() => setLocation('/trade-desk')} data-testid="button-view-trades-cta">
                    <ArrowRight className="h-4 w-4 mr-2" />
                    View Active Trades
                  </Button>
                </CardContent>
              </Card>
            </div>
          )}
        </div>
      </section>

      {/* Pricing Section */}
      <section className="py-16 md:py-24 bg-muted/30" id="pricing">
        <div className="container mx-auto px-6">
          <div className="text-center mb-12">
            <Badge variant="secondary" className="mb-4">
              <LineChart className="h-3 w-3 mr-1" />
              Pricing Plans
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Choose Your Plan
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto mb-8">
              Start free and upgrade as you grow
            </p>
            
            {/* Billing Toggle */}
            <div className="flex items-center justify-center gap-4" data-testid="billing-toggle">
              <span className={`text-sm font-medium ${billingPeriod === 'monthly' ? 'text-foreground' : 'text-muted-foreground'}`}>
                Monthly
              </span>
              <button
                onClick={() => setBillingPeriod(billingPeriod === 'monthly' ? 'yearly' : 'monthly')}
                className={`relative inline-flex h-7 w-14 items-center rounded-full transition-colors ${
                  billingPeriod === 'yearly' ? 'bg-primary' : 'bg-muted'
                }`}
                data-testid="button-billing-toggle"
              >
                <span
                  className={`inline-block h-5 w-5 transform rounded-full bg-white shadow-md transition-transform ${
                    billingPeriod === 'yearly' ? 'translate-x-8' : 'translate-x-1'
                  }`}
                />
              </button>
              <div className="flex items-center gap-2">
                <span className={`text-sm font-medium ${billingPeriod === 'yearly' ? 'text-foreground' : 'text-muted-foreground'}`}>
                  Yearly
                </span>
                <Badge variant="secondary" className="text-xs bg-green-500/10 text-green-500 border-green-500/20">
                  Save 17%
                </Badge>
              </div>
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-6 max-w-3xl mx-auto">
            {/* Free Tier */}
            <Card data-testid="card-pricing-free">
              <CardContent className="p-8 flex flex-col h-full">
                <div className="mb-6">
                  <h3 className="text-xl font-bold mb-2">Free</h3>
                  <div className="flex items-baseline gap-1 mb-2">
                    <span className="text-4xl font-bold">$0</span>
                    <span className="text-muted-foreground">/month</span>
                  </div>
                  <p className="text-sm text-muted-foreground">Preview the platform</p>
                </div>
                
                <ul className="space-y-3 mb-8 flex-1">
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span className="text-sm">5 trade ideas per day</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Delayed market data (15min)</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span className="text-sm">7-day performance history</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Stocks & crypto only</span>
                  </li>
                </ul>
                
                <Button 
                  variant="outline" 
                  className="w-full"
                  onClick={() => setLocation('/signup')}
                  data-testid="button-pricing-free"
                >
                  Get Started Free
                </Button>
              </CardContent>
            </Card>

            {/* Advanced Tier */}
            <Card className="relative border-primary" data-testid="card-pricing-advanced">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                <Badge>Most Popular</Badge>
              </div>
              <CardContent className="p-8 flex flex-col h-full">
                <div className="mb-6">
                  <h3 className="text-xl font-bold mb-2">Advanced</h3>
                  <div className="flex items-baseline gap-1 mb-2">
                    <span className="text-4xl font-bold text-primary">
                      ${billingPeriod === 'monthly' ? '39' : '33'}
                    </span>
                    <span className="text-muted-foreground">/month</span>
                  </div>
                  {billingPeriod === 'yearly' && (
                    <p className="text-xs text-green-500">Billed $390/year (save $78)</p>
                  )}
                  <p className="text-sm text-muted-foreground">Full stock & crypto access</p>
                </div>
                
                <ul className="space-y-3 mb-8 flex-1">
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm font-medium">Everything in Free</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Unlimited trade ideas</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Real-time market data</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm">10 chart analyses per day</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm">25 AI generations per day</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Full performance history</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <Check className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-sm">Discord alerts</span>
                  </li>
                </ul>
                
                <Button 
                  className="w-full"
                  onClick={() => setLocation('/signup')}
                  data-testid="button-pricing-advanced"
                >
                  <Sparkles className="h-4 w-4 mr-2" />
                  Get Advanced
                </Button>
              </CardContent>
            </Card>

          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-16 md:py-24" id="faq">
        <div className="container mx-auto px-6">
          <div className="text-center mb-12">
            <Badge variant="secondary" className="mb-4">
              <Activity className="h-3 w-3 mr-1" />
              FAQ
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Frequently Asked Questions
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Everything you need to know about QuantEdge
            </p>
          </div>

          <div className="max-w-3xl mx-auto">
            <Accordion type="single" collapsible className="space-y-3">
              <AccordionItem value="accuracy" className="border rounded-xl px-6" data-testid="accordion-faq-accuracy">
                <AccordionTrigger className="text-left font-medium hover:no-underline py-4" data-testid="trigger-faq-accuracy">
                  How accurate are the trade signals?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-4" data-testid="content-faq-accuracy">
                  Our quantitative engine uses research-backed strategies with historical win rates of 75-91%. 
                  Every trade is tracked transparently with actual win/loss results published to our performance ledger.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="trading-styles" className="border rounded-xl px-6" data-testid="accordion-faq-styles">
                <AccordionTrigger className="text-left font-medium hover:no-underline py-4" data-testid="trigger-faq-styles">
                  Can I use QuantEdge for different trading styles?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-4" data-testid="content-faq-styles">
                  Yes! QuantEdge supports day trading, swing trading, and position trading. 
                  Each trade idea includes holding period recommendations optimized for the opportunity.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="markets" className="border rounded-xl px-6" data-testid="accordion-faq-markets">
                <AccordionTrigger className="text-left font-medium hover:no-underline py-4" data-testid="trigger-faq-markets">
                  What markets does QuantEdge cover?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-4" data-testid="content-faq-markets">
                  QuantEdge analyzes US equities, options, cryptocurrencies, and futures contracts. 
                  Real-time data is sourced from Yahoo Finance, Alpha Vantage, Tradier, and CoinGecko.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="dual-engine" className="border rounded-xl px-6" data-testid="accordion-faq-dual-engine">
                <AccordionTrigger className="text-left font-medium hover:no-underline py-4" data-testid="trigger-faq-dual-engine">
                  How does the dual-engine system work?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-4" data-testid="content-faq-dual-engine">
                  Our AI Engine uses multi-provider LLMs for contextual insights. The Quantitative Engine runs research-backed technical strategies. 
                  When both engines agree, win rates historically increase by 18%.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="beginners" className="border rounded-xl px-6" data-testid="accordion-faq-beginners">
                <AccordionTrigger className="text-left font-medium hover:no-underline py-4" data-testid="trigger-faq-beginners">
                  Is QuantEdge suitable for beginners?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-4" data-testid="content-faq-beginners">
                  QuantEdge is designed as an educational research platform. Every trade idea includes explainability features 
                  to help you understand the reasoning. We recommend paper trading while learning.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="premium" className="border rounded-xl px-6" data-testid="accordion-faq-premium">
                <AccordionTrigger className="text-left font-medium hover:no-underline py-4" data-testid="trigger-faq-premium">
                  What's the difference between the plans?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-4" data-testid="content-faq-premium">
                  <strong>Free</strong> gives you 5 trade ideas per day with delayed market data to preview the platform. 
                  <strong>Advanced</strong> ($39/mo) unlocks unlimited trade ideas, real-time data, chart analysis, Discord alerts, and full performance history.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 md:py-24 bg-primary/5">
        <div className="container mx-auto px-6 text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Ready to Trade with Precision?
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto mb-8">
            Join thousands of traders using AI-powered analysis to make smarter trading decisions.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Button size="lg" onClick={() => setLocation('/signup')} data-testid="button-cta-signup">
              Get Started Free
              <ArrowRight className="h-5 w-5 ml-2" />
            </Button>
            <Button size="lg" variant="outline" onClick={() => setLocation('/chart-analysis')} data-testid="button-cta-demo">
              Try Chart Analysis
            </Button>
          </div>
        </div>
      </section>

      {/* Professional Footer */}
      <footer className="border-t py-12 md:py-16" data-testid="footer">
        <div className="container mx-auto px-6">
          <div className="grid md:grid-cols-4 gap-8 mb-12">
            {/* Brand Column */}
            <div className="md:col-span-1">
              <div className="flex items-center gap-2 mb-4">
                <img src={quantEdgeLogoUrl} alt="QuantEdge" className="h-8 w-8 object-contain" />
                <span className="font-bold text-lg">QuantEdge</span>
              </div>
              <p className="text-sm text-muted-foreground mb-4">
                AI-powered trading intelligence for professional traders.
              </p>
              <div className="flex items-center gap-3">
                <Button variant="ghost" size="icon" data-testid="link-social-twitter">
                  <Twitter className="h-4 w-4" />
                </Button>
                <Button variant="ghost" size="icon" data-testid="link-social-linkedin">
                  <Linkedin className="h-4 w-4" />
                </Button>
                <Button variant="ghost" size="icon" data-testid="link-social-github">
                  <Github className="h-4 w-4" />
                </Button>
              </div>
            </div>

            {/* Product Column */}
            <div>
              <h4 className="font-semibold mb-4">Product</h4>
              <ul className="space-y-3">
                <li>
                  <button 
                    onClick={() => scrollToSection('features')} 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-features"
                  >
                    Features
                  </button>
                </li>
                <li>
                  <Link 
                    href="/chart-database" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-chart-database"
                  >
                    Chart Database
                  </Link>
                </li>
                <li>
                  <Link 
                    href="/trade-desk" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-dashboard"
                  >
                    Dashboard
                  </Link>
                </li>
                <li>
                  <button 
                    onClick={() => scrollToSection('pricing')} 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-pricing"
                  >
                    Pricing
                  </button>
                </li>
              </ul>
            </div>

            {/* Resources Column */}
            <div>
              <h4 className="font-semibold mb-4">Resources</h4>
              <ul className="space-y-3">
                <li>
                  <Link 
                    href="/academy" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-academy"
                  >
                    Academy
                  </Link>
                </li>
                <li>
                  <Link 
                    href="/blog" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-blog"
                  >
                    Blog
                  </Link>
                </li>
                <li>
                  <button 
                    onClick={() => scrollToSection('success-stories')} 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-success-stories"
                  >
                    Success Stories
                  </button>
                </li>
                <li>
                  <Link 
                    href="/terms" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-terms"
                  >
                    Terms of Service
                  </Link>
                </li>
                <li>
                  <Link 
                    href="/privacy" 
                    className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    data-testid="footer-link-privacy"
                  >
                    Privacy Policy
                  </Link>
                </li>
              </ul>
            </div>

            {/* Get Started Column */}
            <div>
              <h4 className="font-semibold mb-4">Get Started</h4>
              <p className="text-sm text-muted-foreground mb-4">
                Start analyzing charts with AI precision today.
              </p>
              <Button onClick={() => setLocation('/signup')} className="w-full" data-testid="footer-button-signup">
                Create Free Account
              </Button>
            </div>
          </div>

          {/* Bottom Bar */}
          <div className="border-t pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
            <p className="text-sm text-muted-foreground">
              © {new Date().getFullYear()} QuantEdge Research. All rights reserved.
            </p>
            <p className="text-xs text-muted-foreground text-center md:text-right">
              <span className="text-destructive font-medium">NOT FINANCIAL ADVICE</span> • Educational research platform. Trading involves substantial risk.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
