import { useQuery } from "@tanstack/react-query";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import type { TradeIdea } from "@shared/schema";
import { TrendingUp, CheckCircle2, Award, Target, BarChart3, ArrowRight } from "lucide-react";
import { useLocation } from "wouter";
import { SEOHead } from "@/components/seo-head";

export default function SuccessStories() {
  const [, setLocation] = useLocation();

  const { data: tradeIdeas = [], isLoading } = useQuery<TradeIdea[]>({
    queryKey: ['/api/trade-ideas'],
  });

  const winningTrades = tradeIdeas
    .filter(idea => idea.outcomeStatus === 'hit_target' && (idea.percentGain || 0) > 5)
    .sort((a, b) => (b.percentGain || 0) - (a.percentGain || 0))
    .slice(0, 20);

  return (
    <div className="min-h-screen bg-background">
      <SEOHead pageKey="successStories" />
      
      {/* Hero Section */}
      <section className="border-b border-slate-800 py-12 md:py-16 bg-gradient-to-b from-slate-900/50 to-background">
        <div className="container mx-auto px-6">
          <div className="text-center mb-10">
            <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-3">
              Verified Results
            </p>
            <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold tracking-tight mb-4">
              Success Stories
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Winning trades from our platform. Every result you see here is a real trade generated by our AI and quantitative engines.
            </p>
          </div>

          {/* Platform Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto">
            <div className="glass-card rounded-lg p-5 text-center hover-elevate">
              <div className="h-10 w-10 rounded-lg bg-gradient-to-br from-green-500 to-green-600 flex items-center justify-center mx-auto mb-3 shadow-lg shadow-green-500/20">
                <TrendingUp className="h-5 w-5 text-white" />
              </div>
              <div className="text-2xl font-bold font-mono tabular-nums text-foreground mb-1">
                {winningTrades.length}
              </div>
              <div className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Winning Trades</div>
            </div>
            <div className="glass-card rounded-lg p-5 text-center hover-elevate">
              <div className="h-10 w-10 rounded-lg bg-gradient-to-br from-cyan-500 to-cyan-600 flex items-center justify-center mx-auto mb-3 shadow-lg shadow-cyan-500/20">
                <Target className="h-5 w-5 text-white" />
              </div>
              <div className="text-2xl font-bold font-mono tabular-nums text-foreground mb-1">
                {winningTrades.length > 0
                  ? Math.round(winningTrades.reduce((sum, t) => sum + (t.percentGain || 0), 0) / winningTrades.length)
                  : 0}%
              </div>
              <div className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Avg Gain</div>
            </div>
            <div className="glass-card rounded-lg p-5 text-center hover-elevate">
              <div className="h-10 w-10 rounded-lg bg-gradient-to-br from-amber-500 to-amber-600 flex items-center justify-center mx-auto mb-3 shadow-lg shadow-amber-500/20">
                <BarChart3 className="h-5 w-5 text-white" />
              </div>
              <div className="text-2xl font-bold font-mono tabular-nums text-foreground mb-1">
                {winningTrades.length > 0
                  ? Math.max(...winningTrades.map(t => t.percentGain || 0)).toFixed(1)
                  : 0}%
              </div>
              <div className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Biggest Win</div>
            </div>
            <div className="glass-card rounded-lg p-5 text-center hover-elevate">
              <div className="h-10 w-10 rounded-lg bg-gradient-to-br from-green-500 to-emerald-600 flex items-center justify-center mx-auto mb-3 shadow-lg shadow-green-500/20">
                <CheckCircle2 className="h-5 w-5 text-white" />
              </div>
              <div className="text-2xl font-bold font-mono tabular-nums text-foreground mb-1">100%</div>
              <div className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Hit Target</div>
            </div>
          </div>
        </div>
      </section>

      {/* Winning Trades Grid */}
      <section className="container mx-auto px-6 py-12 md:py-16">
        <div className="mb-8">
          <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-2">
            Performance History
          </p>
          <h2 className="text-xl font-semibold mb-1">Recent Winning Trades</h2>
          <p className="text-sm text-muted-foreground">
            Top performing trades that hit their profit targets
          </p>
        </div>

        {isLoading ? (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[1, 2, 3, 4, 5, 6].map(i => (
              <div key={i} className="glass-card rounded-lg p-6">
                <Skeleton className="h-24 w-full" />
              </div>
            ))}
          </div>
        ) : winningTrades.length === 0 ? (
          <div className="glass-card rounded-lg p-12 text-center">
            <div className="h-16 w-16 rounded-xl bg-gradient-to-br from-slate-600 to-slate-700 flex items-center justify-center mx-auto mb-4">
              <Award className="h-8 w-8 text-slate-300" />
            </div>
            <h3 className="text-xl font-semibold mb-2">No Success Stories Yet</h3>
            <p className="text-muted-foreground mb-6">
              Check back soon for winning trades from our platform
            </p>
            <Button 
              onClick={() => setLocation('/trade-desk')} 
              className="bg-cyan-500 hover:bg-cyan-400 text-slate-950"
              data-testid="button-view-trades"
            >
              <ArrowRight className="h-4 w-4 mr-2" />
              View Research Desk
            </Button>
          </div>
        ) : (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {winningTrades.map((trade, index) => (
              <div
                key={trade.id}
                className="glass-card rounded-lg overflow-visible hover-elevate"
                data-testid={`card-success-story-${index}`}
              >
                <div className="p-6">
                  <div className="flex items-start justify-between gap-4 mb-4">
                    <div>
                      <h3 className="text-xl font-bold font-mono mb-1">{trade.symbol}</h3>
                      <Badge 
                        className={trade.direction === 'long' 
                          ? 'bg-green-500/10 text-green-400 border-green-500/30' 
                          : 'bg-red-500/10 text-red-400 border-red-500/30'
                        }
                      >
                        {trade.direction.toUpperCase()}
                      </Badge>
                    </div>
                    <div className="text-right">
                      <div className="text-2xl font-bold font-mono tabular-nums text-green-400">
                        +{trade.percentGain?.toFixed(1)}%
                      </div>
                      <CheckCircle2 className="h-4 w-4 text-green-400 ml-auto mt-1" />
                    </div>
                  </div>

                  <div className="space-y-2 mb-4">
                    <div className="flex justify-between items-center text-sm">
                      <span className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Entry</span>
                      <span className="font-mono font-semibold tabular-nums">
                        ${trade.entryPrice.toFixed(2)}
                      </span>
                    </div>
                    <div className="flex justify-between items-center text-sm">
                      <span className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Exit</span>
                      <span className="font-mono font-semibold tabular-nums text-green-400">
                        ${(trade.exitPrice || trade.targetPrice).toFixed(2)}
                      </span>
                    </div>
                    <div className="flex justify-between items-center text-sm">
                      <span className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Source</span>
                      <Badge 
                        variant="outline" 
                        className={
                          trade.source === 'ai' 
                            ? 'bg-purple-500/10 text-purple-400 border-purple-500/30 text-xs' 
                            : trade.source === 'quant'
                              ? 'bg-blue-500/10 text-blue-400 border-blue-500/30 text-xs'
                              : 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30 text-xs'
                        }
                      >
                        {trade.source.toUpperCase()}
                      </Badge>
                    </div>
                  </div>

                  {trade.catalyst && (
                    <div className="stat-glass rounded-lg p-3 text-xs text-muted-foreground leading-relaxed">
                      "{trade.catalyst.slice(0, 100)}{trade.catalyst.length > 100 ? '...' : ''}"
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* CTA Section */}
      <section className="border-t border-slate-800 py-12 md:py-16 bg-gradient-to-b from-background to-slate-900/30">
        <div className="container mx-auto px-6 text-center">
          <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-3">
            Start Trading
          </p>
          <h2 className="text-2xl sm:text-3xl font-semibold mb-4">Ready to Start Your Success Story?</h2>
          <p className="text-muted-foreground mb-8 max-w-xl mx-auto leading-relaxed">
            Join traders using AI-powered analysis and quantitative signals to find winning opportunities
          </p>
          <Button
            onClick={() => setLocation('/trade-desk')}
            className="bg-cyan-500 hover:bg-cyan-400 text-slate-950"
            data-testid="button-get-started"
          >
            Get Started <ArrowRight className="ml-2 h-4 w-4" />
          </Button>
        </div>
      </section>
    </div>
  );
}
