import { useQuery } from "@tanstack/react-query";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import type { TradeIdea } from "@shared/schema";
import { TrendingUp, CheckCircle2, Award, Target, Clock, BarChart3, ArrowRight } from "lucide-react";
import { useLocation } from "wouter";

export default function SuccessStories() {
  const [, setLocation] = useLocation();

  const { data: tradeIdeas = [], isLoading } = useQuery<TradeIdea[]>({
    queryKey: ['/api/trade-ideas'],
  });

  const winningTrades = tradeIdeas
    .filter(idea => idea.outcomeStatus === 'hit_target' && (idea.percentGain || 0) > 5)
    .sort((a, b) => (b.percentGain || 0) - (a.percentGain || 0))
    .slice(0, 20);

  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section */}
      <section className="border-b py-12 md:py-16 bg-gradient-to-b from-primary/5 to-background">
        <div className="container mx-auto px-6">
          <div className="text-center mb-8">
            <Badge variant="secondary" className="mb-4 neon-accent">
              <Award className="h-3 w-3 mr-1" />
              Real Results
            </Badge>
            <h1 className="text-4xl md:text-5xl font-bold mb-4 text-display">
              Success Stories
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Winning trades from our platform. Every result you see here is a real trade generated by our AI and quantitative engines.
            </p>
          </div>

          {/* Platform Stats */}
          <div className="grid md:grid-cols-4 gap-6 max-w-5xl mx-auto">
            <div className="glass-card rounded-xl p-6 text-center">
              <TrendingUp className="h-8 w-8 text-green-500 mx-auto mb-3" />
              <div className="text-3xl font-bold text-gradient mb-1">
                {winningTrades.length}
              </div>
              <div className="text-sm text-muted-foreground">Winning Trades</div>
            </div>
            <div className="glass-card rounded-xl p-6 text-center">
              <Target className="h-8 w-8 text-cyan-500 mx-auto mb-3" />
              <div className="text-3xl font-bold text-gradient mb-1">
                {winningTrades.length > 0
                  ? Math.round(winningTrades.reduce((sum, t) => sum + (t.percentGain || 0), 0) / winningTrades.length)
                  : 0}%
              </div>
              <div className="text-sm text-muted-foreground">Avg Gain</div>
            </div>
            <div className="glass-card rounded-xl p-6 text-center">
              <BarChart3 className="h-8 w-8 text-amber-400 mx-auto mb-3" />
              <div className="text-3xl font-bold text-gradient mb-1">
                {winningTrades.length > 0
                  ? Math.max(...winningTrades.map(t => t.percentGain || 0)).toFixed(1)
                  : 0}%
              </div>
              <div className="text-sm text-muted-foreground">Biggest Win</div>
            </div>
            <div className="glass-card rounded-xl p-6 text-center">
              <CheckCircle2 className="h-8 w-8 text-green-500 mx-auto mb-3" />
              <div className="text-3xl font-bold text-gradient mb-1">100%</div>
              <div className="text-sm text-muted-foreground">Hit Target</div>
            </div>
          </div>
        </div>
      </section>

      {/* Winning Trades Grid */}
      <section className="container mx-auto px-6 py-12 md:py-16">
        <div className="mb-8">
          <h2 className="text-2xl font-bold mb-2">Recent Winning Trades</h2>
          <p className="text-muted-foreground">
            Top performing trades that hit their profit targets
          </p>
        </div>

        {isLoading ? (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[1, 2, 3, 4, 5, 6].map(i => (
              <Card key={i}>
                <CardContent className="p-6">
                  <Skeleton className="h-24 w-full" />
                </CardContent>
              </Card>
            ))}
          </div>
        ) : winningTrades.length === 0 ? (
          <Card>
            <CardContent className="p-12 text-center">
              <Award className="h-16 w-16 text-muted-foreground mx-auto mb-4" />
              <h3 className="text-xl font-semibold mb-2">No Success Stories Yet</h3>
              <p className="text-muted-foreground mb-6">
                Check back soon for winning trades from our platform
              </p>
              <Button onClick={() => setLocation('/trade-desk')} data-testid="button-view-trades">
                <ArrowRight className="h-4 w-4 mr-2" />
                View Trade Desk
              </Button>
            </CardContent>
          </Card>
        ) : (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {winningTrades.map((trade, index) => (
              <div
                key={trade.id}
                className="gradient-border-card card-tilt"
                data-testid={`card-success-story-${index}`}
              >
                <Card className="border-0 bg-transparent h-full">
                  <CardContent className="p-6">
                    <div className="flex items-start justify-between mb-4">
                      <div>
                        <h3 className="text-2xl font-bold mb-1">{trade.symbol}</h3>
                        <Badge variant={trade.direction === 'long' ? 'default' : 'destructive'}>
                          {trade.direction.toUpperCase()}
                        </Badge>
                      </div>
                      <div className="text-right">
                        <div className="text-4xl font-bold text-green-500">
                          +{trade.percentGain?.toFixed(1)}%
                        </div>
                        <CheckCircle2 className="h-5 w-5 text-green-500 ml-auto mt-1" />
                      </div>
                    </div>

                    <div className="space-y-3 mb-4">
                      <div className="flex justify-between text-sm">
                        <span className="text-muted-foreground">Entry</span>
                        <span className="font-mono font-semibold">
                          ${trade.entryPrice.toFixed(2)}
                        </span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-muted-foreground">Exit</span>
                        <span className="font-mono font-semibold text-green-500">
                          ${(trade.exitPrice || trade.targetPrice).toFixed(2)}
                        </span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-muted-foreground">Source</span>
                        <Badge variant="outline" className="text-xs">
                          {trade.source}
                        </Badge>
                      </div>
                    </div>

                    {trade.catalyst && (
                      <div className="glass-card rounded-lg p-3 text-xs text-muted-foreground">
                        "{trade.catalyst.slice(0, 100)}{trade.catalyst.length > 100 ? '...' : ''}"
                      </div>
                    )}
                  </CardContent>
                </Card>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* CTA Section */}
      <section className="border-t py-12 md:py-16 bg-gradient-to-b from-background to-primary/5">
        <div className="container mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to Start Your Success Story?</h2>
          <p className="text-lg text-muted-foreground mb-6 max-w-2xl mx-auto">
            Join traders using AI-powered analysis and quantitative signals to find winning opportunities
          </p>
          <Button
            onClick={() => setLocation('/trade-desk')}
            className="btn-magnetic neon-accent"
            data-testid="button-get-started"
          >
            <ArrowRight className="h-4 w-4 mr-2" />
            Get Started
          </Button>
        </div>
      </section>
    </div>
  );
}
