/**
 * Auto-fill a thesis file's [VERIFY] slots from live services.
 *
 * Usage:
 *   tsx scripts/fill-thesis.ts BB                     # fills theses/<latest>-BB.md
 *   tsx scripts/fill-thesis.ts BB --file=theses/2026-05-BB.md
 *   tsx scripts/fill-thesis.ts BB --dry              # print without writing
 *
 * Pulls:
 *   - Spot price from realtime-pricing-service
 *   - StockTwits per-symbol sentiment from social-sentiment-scanner
 *   - Sentiment scorer (analyst consensus + news + social composite)
 *
 * Conservative on purpose: only fills the four slots in the header table
 * plus a stamped sentiment snapshot at the bottom. Everything else (FA,
 * TA levels, catalysts) stays manual — those need a human read.
 */
import { readFile, writeFile, readdir } from 'fs/promises';
import path from 'path';

async function main() {
  const args = process.argv.slice(2);
  const ticker = (args.find(a => !a.startsWith('--')) ?? '').toUpperCase();
  if (!ticker) {
    console.error('usage: tsx scripts/fill-thesis.ts <TICKER> [--file=path] [--dry]');
    process.exit(1);
  }
  const dry = args.includes('--dry');
  const explicitFile = args.find(a => a.startsWith('--file='))?.split('=')[1];

  const thesesDir = path.resolve(process.cwd(), 'theses');
  let target = explicitFile ?? '';
  if (!target) {
    const files = await readdir(thesesDir);
    const matches = files
      .filter(f => f.endsWith(`-${ticker}.md`))
      .sort()
      .reverse();
    if (!matches.length) {
      console.error(`no thesis file found for ${ticker} in ${thesesDir}`);
      process.exit(1);
    }
    target = path.join(thesesDir, matches[0]);
  }

  console.log(`[fill-thesis] target: ${target}`);
  const original = await readFile(target, 'utf-8');

  // Lazy import server modules so the script also works in environments
  // where some env keys (Tradier, etc.) are missing — failures fall back
  // gracefully and just leave [VERIFY] in place.
  let price: number | null = null;
  try {
    const { getRealtimeQuote } = await import('../server/realtime-pricing-service');
    const q = await getRealtimeQuote(ticker, 'stock');
    if (q && Number.isFinite(q.price)) price = q.price;
  } catch (err: any) {
    console.warn(`[fill-thesis] price fetch failed: ${err?.message ?? err}`);
  }

  let stocktwitsLine = '';
  try {
    const { getSymbolSocialSentiment } = await import('../server/social-sentiment-scanner');
    const s = await getSymbolSocialSentiment(ticker);
    const st = s.stocktwits;
    if (st && st.messageCount >= 5) {
      stocktwitsLine =
        `${st.bullishCount}🐂 / ${st.bearishCount}🐻 across ${st.messageCount} msgs ` +
        `(score ${st.sentimentScore}, ${s.composite.label}, ${s.composite.confidence} conf)`;
    } else if (st) {
      stocktwitsLine = `low volume — only ${st.messageCount} StockTwits msgs`;
    } else {
      stocktwitsLine = 'StockTwits stream unavailable';
    }
  } catch (err: any) {
    console.warn(`[fill-thesis] sentiment fetch failed: ${err?.message ?? err}`);
    stocktwitsLine = 'fetch failed';
  }

  let scorerLine = '';
  try {
    const { sentimentScorer } = await import('../server/sentiment-scorer');
    const r = await sentimentScorer.score(ticker);
    scorerLine = `composite ${r.score}/100`;
  } catch (err: any) {
    console.warn(`[fill-thesis] sentiment scorer failed: ${err?.message ?? err}`);
  }

  const ts = new Date().toISOString();
  const stamped =
    `\n\n## Auto-filled snapshot (${ts})\n\n` +
    `- **Spot price:** ${price !== null ? `$${price.toFixed(2)}` : '[fetch failed — leave [VERIFY]]'}\n` +
    `- **StockTwits:** ${stocktwitsLine}\n` +
    `- **Sentiment scorer:** ${scorerLine || '[fetch failed]'}\n` +
    `- _Generated by_ \`scripts/fill-thesis.ts\`. Manual TA/FA fills still required.\n`;

  // Replace the spot-at-open [VERIFY] only if it's still a placeholder.
  let updated = original;
  if (price !== null) {
    updated = updated.replace(
      /(\*\*Spot price at open:\*\*\s*)`?\[VERIFY\]`?/i,
      `$1$${price.toFixed(2)}`
    );
  }

  // Append (or replace if exists) the auto-filled snapshot section.
  const existingSnapshot = /\n## Auto-filled snapshot[\s\S]*$/;
  if (existingSnapshot.test(updated)) {
    updated = updated.replace(existingSnapshot, stamped);
  } else {
    updated += stamped;
  }

  if (dry) {
    console.log('--- preview (dry-run) ---');
    console.log(stamped);
    return;
  }

  await writeFile(target, updated, 'utf-8');
  console.log(`[fill-thesis] wrote ${target}`);
}

main().catch(err => {
  console.error('[fill-thesis] fatal:', err);
  process.exit(1);
});
