import { AlertTriangle, Info } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";

interface RiskDisclosureProps {
  variant?: 'full' | 'compact';
  engineVersion?: string;
  className?: string;
}

export function RiskDisclosure({ variant = 'compact', engineVersion, className = '' }: RiskDisclosureProps) {
  if (variant === 'compact') {
    return (
      <Alert className={`border-amber-500/30 bg-amber-500/5 ${className}`} data-testid="alert-risk-disclosure">
        <AlertTriangle className="h-4 w-4 text-amber-500" />
        <AlertDescription className="text-sm">
          <strong className="font-semibold">Educational Research Only:</strong> This platform provides quantitative trade ideas for educational and research purposes.{' '}
          <span className="text-muted-foreground">Not financial advice. Markets are risky. Always do your own research and consult a licensed advisor before trading.</span>
          {engineVersion && (
            <Badge variant="outline" className="ml-2 text-xs">
              Engine: {engineVersion}
            </Badge>
          )}
        </AlertDescription>
      </Alert>
    );
  }

  return (
    <Card className={`border-amber-500/30 bg-gradient-to-br from-amber-500/5 to-transparent ${className}`} data-testid="card-risk-disclosure">
      <CardHeader>
        <CardTitle className="text-lg flex items-center gap-2">
          <AlertTriangle className="h-5 w-5 text-amber-500" />
          Risk Disclosure & Legal Notice
          {engineVersion && (
            <Badge variant="outline" className="ml-auto">
              Model: {engineVersion}
            </Badge>
          )}
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4 text-sm">
        <div className="space-y-2">
          <div className="flex items-start gap-3">
            <Info className="h-4 w-4 text-blue-500 mt-0.5 shrink-0" />
            <div>
              <p className="font-semibold text-foreground">Educational & Research Purposes Only</p>
              <p className="text-muted-foreground">
                QuantEdge Research is a quantitative trading research platform designed for educational purposes and strategy development.
                All trade ideas, analyses, and predictions are generated by algorithmic models for research purposes only.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3">
            <AlertTriangle className="h-4 w-4 text-amber-500 mt-0.5 shrink-0" />
            <div>
              <p className="font-semibold text-foreground">Not Financial Advice</p>
              <p className="text-muted-foreground">
                This platform does NOT provide personalized financial advice, investment recommendations, or trading signals for actual execution.
                Do NOT use these ideas as the sole basis for making investment decisions.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3">
            <AlertTriangle className="h-4 w-4 text-red-500 mt-0.5 shrink-0" />
            <div>
              <p className="font-semibold text-foreground">Risk Warning</p>
              <p className="text-muted-foreground">
                Trading stocks, options, and cryptocurrencies involves substantial risk of loss and is not suitable for all investors.
                Past performance is not indicative of future results. You may lose some or all of your invested capital.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3">
            <Info className="h-4 w-4 text-blue-500 mt-0.5 shrink-0" />
            <div>
              <p className="font-semibold text-foreground">Model Limitations & Data Quality</p>
              <p className="text-muted-foreground">
                Quantitative models have inherent limitations and assumptions. Historical data may be incomplete or delayed.
                Technical indicators can produce false signals. No model can predict market movements with certainty.
              </p>
            </div>
          </div>
        </div>

        <div className="border-t border-border pt-3 mt-3">
          <p className="text-xs text-muted-foreground">
            <strong className="text-foreground">Recommendation:</strong> Always conduct your own due diligence, understand the risks involved,
            and consult with a licensed financial advisor or investment professional before making any trading decisions.
            Use proper position sizing and risk management techniques appropriate for your situation.
          </p>
        </div>

        <div className="bg-muted/30 border border-border/50 rounded-lg p-3 text-xs text-muted-foreground">
          <p className="font-mono">
            <strong className="text-foreground">Model Governance:</strong> All trade ideas are generated with full audit trails including
            engine version, ML weights snapshot, and generation timestamps for research integrity and model risk management compliance.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
